--these tables allow the strings in the game to be translated to any number of other languages

function translate(params)
  local msg
  local currentLanguage = controlPanelSettings['currentLanguage']
  if type(params) == 'table' then
      msg = params[1]
  else
      msg = params
  end
  if LOCALIZED_STRINGS[currentLanguage] ~= nil and LOCALIZED_STRINGS[currentLanguage][msg] ~= nil then
      msg = LOCALIZED_STRINGS[currentLanguage][msg]
  end
  if type(params) == 'table' then
      for i = 2, #params do
          msg = string.gsub(msg, params[i][1], params[i][2])
      end
  end
  return msg
end

LOCALIZED_TAUNTS = {
    ['en-us'] = {
        "Hehehehe...",
        ":)",
        "Let's see if you can handle this.",
        "You've just been served, son.",
        "Let me guess, you're gonna whine about how I cheat now."
    },
    ['nl-NL'] = {
      "Hehehehe...",
      ":)",
      "Eens zien of je dit zag aankomen.",
      "Laat me raden, nu ga je zeuren dat ik valsspeel."
    }
    ['zh-tw'] = {
        "嘿嘿嘿....",
        "接招!",
        ":)"
    }
}
--string substitutions follow this basic pattern, although it ultimately can be anything:
-- {c#} = Color of a player
-- {p#} = Name of a player
-- {f#} = Figure name
-- {n#} = Number
-- {s#} = String
LOCALIZED_STRINGS = {
  ['en-us'] = {

    --Button Labels

    ["BUTTON_LABEL_START_GAME"] = "Start\nGame",
    ["BUTTON_LABEL_END_GAME"] = "End game\n(score\npoints)",
    ["BUTTON_LABEL_SCORE_SUMMARY"] = "Score\nSummary",
    ["BUTTON_LABEL_SKIP_TURN"] = "Skip\nTurn",
    ["BUTTON_LABEL_MARKERS"] = "Show\nMarkers:\n",
    ["BUTTON_LABEL_PROMPT_PLACE_FIGURE"] = "Place a figure\nOR",
    ["BUTTON_LABEL_SKIP_PLACING_FIGURE"] = "Skip placing\nfigure",
    ["BUTTON_LABEL_PLACE_GOLD"] = "Place\nGold",
    ["BUTTON_LABEL_SEDUCE_KNIGHT"] = "Seduce\nknight",
    ["BUTTON_LABEL_RETRIEVE_ABBOT"] = "Retrieve\nabbot",
    ["BUTTON_LABEL_PROMPT_PLACE_PHANTOM"] = "Place a phantom\nOR",
    ["BUTTON_LABEL_SKIP_PHANTOM"] = "Skip placing\nphantom",
    ["BUTTON_LABEL_SKIP_TOWER_CAPTURE"] = "Skip capturing\nfollower",
    ["BUTTON_LABEL_PROMPT_REPLACE_WAGON"] = "Replace your wagon\nOR",
    ["BUTTON_LABEL_SKIP_WAGON"] = "Skip placing\nwagon",
    ["BUTTON_LABEL_PROMPT_COC"] = "Place a figure in\nCity of Carcassonne\nOR",
    ["BUTTON_LABEL_PROMPT_MOVE_COUNT"] = "Move the count\nto another quarter\nOR",
    ["BUTTON_LABEL_SKIP_COUNT"] = "Skip moving\nthe count",
    ["BUTTON_LABEL_RETURN_FOLLOWER"] = "Return\nfollower",
    ["BUTTON_LABEL_CAPTURE"] = "Capture\n{f1}",
    ["BUTTON_LABEL_RANSOM"] = "Ransom\n{f1}",
    ["BUTTON_LABEL_RETURN"] = "Return\n{f1}",
    ["BUTTON_LABEL_EXPAND_FLOCK"] = "Expand the\nflock",
    ["BUTTON_LABEL_HERD_FLOCK"] = "Herd the flock\ninto the stable",
    ["BUTTON_LABEL_TAKE_GOLD"] = "Take\ngold",

    --UI Labels

    ["UI_AI_CALCULATING"] = "AI Calculating Move...",

    --Control Panel Global

    ["LABEL_TILES"] = "Tiles",
    ["LABEL_PREVIOUS_PAGE"] = "Previous Page",
    ["LABEL_NEXT_PAGE"] = "Next Page",
    ["TOOLTIP_ENABLE_ALL"] = "Enable all",
    ["TOOLTIP_NUM_TILES"] = "{n1} tiles",

    --Control Panel pg. 1

      --tooltips

    ["TOOLTIP_AI_HOTSEAT_TOGGLE"] = "Click to toggle between the following:\nAI (Easy)\nAI (Hard)\nHotseat player (of the player clicking)\nNone",
    ["TOOLTIP_BASE_STARTING_TILE"] = "Basic starting tile.",
    ["TOOLTIP_RIVER"] = "12 river tiles that create a winding river before adding normal tiles.",
    ["TOOLTIP_RIVER_II"] = "12 river tiles that feature a fork, dividing the river into 3 parts, and a pig-herd for extra points to farmers.",
    ["TOOLTIP_RIVER_BB5"] = "12 river tiles that feature permanent extra sheep for shepherds.",
    ["TOOLTIP_CITY_OF_CARCASSONNE"] = "The City of Carcassonne starting tiles. Whenever you place a tile that scores points for others, you can store a follower here. These followers can be snuck into features after they are finished, but before they are scored.",
    ["TOOLTIP_WHEEL_OF_FORTUNE"] = "Draw tiles to spin the wheel for an extra element of chance.",

      --messages

    ["MESSAGE_SEAT_OCCUPIED"] = "There is already a player sitting at this seat. Cannot create a hotseat player here.",
    ["MESSAGE_SEAT_ASSIGNED_TO_AI"] = "{c1} has been set to an AI player of difficulty: {s1}",
    ["MESSAGE_SEAT_ASSIGNED_TO_HOTSEAT"] = "{c1} has been set to a hotseat player of {p1}",
    ["MESSAGE_BASE_STARTING_TILE_NOT_ALLOWED"] = "You cannot enable the base starting tile while other starting tiles are enabled.",
    ["MESSAGE_BASE_STARTING_TILE_REMOVED"] = "The base starting tile cannot be combined with this starting tile set. Removing base tile.",
    ["MESSAGE_HOTSEAT_REMOVED"] = "{c1} is no longer a hotseat player",
    ["MESSAGE_TOWER_COUNT_CHANGED"] = "Warning: Tower count has changed to {n1} due to a hotseat/AI player being added/removed.",

    --Control Panel pg. 2

      --labels

    ["LABEL_BASE_GAME"] = "Base Game",
    ["LABEL_MAJOR_EXPANSIONS"] = "Major Expansions",

      --tooltips

    ["TOOLTIP_FOLLOWER"] = "Follower - The Meeple is the basic figure of the player. It can be placed on cities, roads, fields, or cloisters (churches) to take control of that feature.",
    ["TOOLTIP_BIG_FOLLOWER"] = "Follower - The Big Meeple has the same weight as 2 normal followers. This means that only 1 big follower is needed to steal a feature controlled by a player with only 1 normal follower. Even if the player had 2 normal followers, the points would still be shared.",
    ["TOOLTIP_INN"] = "Roads with inns are granted double points when they are finished, but are given no points if they do not finish.",
    ["TOOLTIP_CATHEDRAL"] = "Cities with cathedrals are granted triple points when they are finished (instead of double), but are given no points if they do not finish.",
    ["TOOLTIP_BUILDER"] = "Special Figure - The builder can be placed on any road or city which already has one of your followers. Once placed, anytime the owner of the builder adds to this feature, they will be able to draw an additional tile.",
    ["TOOLTIP_PIG"] = "Special Figure - The pig can be placed on any field that already has one of your followers. At the end of the game, any field containing the pig (that scored points for the player) will score an additional 1 point per city.",
    ["TOOLTIP_TRADE_GOODS"] = "Trade goods icons are present in some cities on Traders and Builders tiles. When a player completes the city (regardless if it was controlled by that player), they will be awarded a token. The player with the most of each type of token will be awarded 10 points at the end of the game. Disabling this does not prevent tiles with trade token icons from being included, but it will prevent the tokens from being awarded.",
    ["TOOLTIP_DRAGON"] = "Neutral Figure - The Dragon will be summoned when a tile with a volcano is drawn. Afterwards, each time a tile with a dragon icon is drawn, the dragon is moved by the players 6 times. The dragon eats most figures on each tile it is moved to. See rules for more details.",
    ["TOOLTIP_FAIRY"] = "Neutral Figure - The fairy can be moved instead of placing a follower on one's turn. The fairy does 3 things: gives 1 point to the follower next to it at the beginning of that follower's turn, gives 3 points when that follower's feature gets finished, and protects the tile from the dragon.",
    ["TOOLTIP_MAGIC_PORTAL"] = "When a tile with a magic portal is drawn, the next follower may be placed on that tile or any other tile already played. The usual rules on follower placement must still be followed.",
    ["TOOLTIP_PRINCESS"] = "When a tile containing a city with the princess is placed, the placing player will have the opportunity to remove one knight (follower) from the connected city instead of placing a follower.",
    ["TOOLTIP_TOWER"] = "A tower can be placed on a Tower foundation or another tower to capture a follower. The taller a tower is built, the further its range.",

      --messages

    ["MESSAGE_FOLLOWER_COUNT_WARNING"] = "Warning: It is strongly recommended to leave the number of followers at 7",
    ["MESSAGE_FOLLOWER_DISABLED_WARNING"] = "Warning: It is strongly recommended not to turn off followers",
    ["MESSAGE_TOWER_COUNT_WARNING"] = "Warning: It is strongly recommended to leave the number of towers at the default number",

    --Control Panel pg. 3

        --labels

    ["LABEL_ROBBER_BARON_SHORT_NAME"] = "Robber", -- This is the shortened form of "Robber Baron", since it doesn't fit on the control panel

      --tooltips

    ["TOOLTIP_ABBEY"] = "The Abbey is a special tile that can be used instead of drawing a random tile from the stack. The abbey can only be placed if it is surrounded on all 4 sides by tiles. The abbey completes all features (road, city, field) that it connects to. A follower can be placed in the abbey as a cloister (8 surrounding tiles finish the feature).",
    ["TOOLTIP_MAYOR"] = "Follower - The Mayor can only be placed on cities. It's strength is the equivalent of 1 normal follower per Pennant in the city.",
    ["TOOLTIP_WAGON"] = "Follower - The Wagon can only be placed on cities, roads, and cloisters. It is scored exactly the same as a normal follower. Once scored, though, the wagon can be moved to any connected feature. A feature is considered connected if it DIRECTLY touches a road. Please see the rules for more details.",
    ["TOOLTIP_BARN"] = "Special Figure - The Barn can only be placed in the corner of 4 tiles, where the corner contains only fields. Any followers in this field are immediately scored and removed. Any followers in fields that are later connected to this field are also removed, but for fewer points. At the end of the game, the barn scores 4 points per completed city in the field. Please see the rules for more details.",
    ["TOOLTIP_KING"] = "The King is awarded to the player that completes the largest city (most tiles). The token is then moved if anyone completes an even bigger city. At the end of the game, the player with the token is awarded 1 point per completed city (anywhere in play).",
    ["TOOLTIP_ROBBER_BARON"] = "The Robber Baron is awarded to the player that completes the longest road (most tiles). The token is then moved if anyone completes an even longer road. At the end of the game, the player with the token is awarded 1 point per completed road (anywhere in play).",
    ["TOOLTIP_SHRINE"] = "6 shrine tiles. Claiming a shrine next to a cloister will challenge that cloister, or vice verca. The first to be completed between the two will score points, while the other will not.",
    ["TOOLTIP_SHEPHERD"] = "Special Figure - The Shepherd can be placed in a field. When placed, the player will draw a random sheep token and add it to the field. Each time the shepherd owner adds a tile to the field, they may draw another token, or herd them for 1 point per sheep. If the player draws a wolf, then all sheep are lost and the shepherd is returned to the supply. See rules for more details.",
    ["TOOLTIP_HILL"] = "The Hill is a feature on some Hills and Sheep tiles. When a player places a follower on any feature on that tile (not the hill itself), that player will break any scoring ties in their favor. See rules for more details. Disabling this option will not prevent tiles containing this feature from being included (it will also not prevent a tile from being 'buried' underneath). Disabling this option will also not prevent tiles containing this feature from being included.",
    ["TOOLTIP_VINEYARD"] = "The Vineyard is a feature on some Hills and Sheep tiles. When a cloister is finished that includes one of these tiles, it will get an additional 3 points per vineyard. This does not apply if the cloister is not finished. See rules for more details. Disabling this option will not prevent tiles containing this feature from being included.",

      --messages

    ["MESSAGE_BASE_STARTING_TILE_NOT_COMPATIBLE_WITH_COC"] = "The base starting tile cannot be combined with the City of Carcassonne. Removing base tile.",

    --Control Panel pg. 4

      --labels

    ["LABEL_MINI_EXPANSIONS"] = "Mini Expansions",
    ["LABEL_WHEEL_SHORT_NAME"] = "Wheel", -- This is the shortened form of "Wheel of Fortune", since it doesn't fit on the control panel
    ["LABEL_WHEEL_TILES"] = "Wheel Tiles",

      --tooltips

    ["TOOLTIP_WHEEL_CROWN"] = "Players may choose to place followers on the crown spaces instead of a tile, awarding points when the pig lands on them.",
    ["TOOLTIP_WHEEL_FORTUNE"] = "When the pig lands on the Fortune event, the current player will be awarded 3 points.",
    ["TOOLTIP_WHEEL_TAX"] = "When the pig lands on the Tax event, each knight will score 1 point for every knight (included itself) and pennant in their city.",
    ["TOOLTIP_WHEEL_TILES"] = "19 tiles containing Wheel of Fortune icons, which spin the wheel.",
    ["TOOLTIP_WHEEL_FAMINE"] = "When the pig lands on the Famine event, every farmer will score 1 point per completed city touching their field.",
    ["TOOLTIP_WHEEL_STORM"] = "When the pig lands on the Storm event, every player will be awarded 1 point for each unused follower in their supply.",
    ["TOOLTIP_WHEEL_INQUISITION"] = "When the pig lands on the Inquisition event, every player will receive 2 points for each monk.",
    ["TOOLTIP_WHEEL_PLAGUE"] = "When the pig lands on the Plague event, each player must return 1 follower from a land tile.",
    ["TOOLTIP_FLIER"] = "The Flier may have a follower placed on it. When done so, a die is rolled to see how far the follower will fly. The player must then place the follower on this tile, if possible, and can even place on a feature that is already occupied (even a cloister). Fields are not allowed.",
    ["TOOLTIP_GOLD"] = "A tile placed with a gold icon will receive a gold bar, along with a neighboring tile. Any player that completes a feature on these tiles will be rewarded the gold, which is worth points at the end of the game.",
    ["TOOLTIP_FERRY"] = "Lakes are operated by ferries, which connect two roads. However, the ferries can change to different roads throughout the game.",

      --messages

    ["MESSAGE_BASE_STARTING_TILE_NOT_COMPATIBLE_WITH_WOF"] = "The base starting tile cannot be combined with the Wheel of Fortune. Removing base tile.",
    ["MESSAGE_WHEEL_DISABLED"] = "This option cannot be enabled when the wheel is disabled.",

    --Control Panel pg. 5

      --labels

    ["LABEL_MICRO_EXPANSIONS"] = "Micro Expansions",

      --tooltips

    ["TOOLTIP_GAMES_QUARTERLY"] = "10 unique tiles to add to the base tile set, along with a special spring tile for river sets which divides the field with a road.",
    ["TOOLTIP_PHANTOMS"] = "A phantom can be placed as a second piece after your usual figure decision.",
    ["TOOLTIP_SPIEL_PROMO"] = "A single city piece. No frills.",
    ["TOOLTIP_WE_GO_TO_CARCASSONNE"] = "2 unique tiles. Baba Yaga's hut is like a cloister, except its value starts at 10 and decreases by 1 point each adjacent tile. The Choice of Bogatyr is a 4-way road piece with a continuous 3-way road section with a 4th road at an intersection.",

    --Control Panel pg. 6

      --labels

    ["LABEL_HOUSE_RULES"] = "House Rules",
    ["LABEL_DISABLE_FEATURE"] = "Disable {s1}",
    ["LABEL_NERF_SMALL_CITIES"] = "Nerf Small Cities",
    ["LABEL_REDUCE_TOWER_RANGE"] = "Reduce tower\ncapture range",
    ["LABEL_RIVER_MIX_TILES"] = "Mix all river\ntiles",
    ["LABEL_RIVER_ALLOW_U_TURNS"] = "Allow\nU-Turns",
    ["LABEL_RIVER_ALLOW_UNCONNECTED"] = "Allow Un-\nconnected",
    ["LABEL_DISABLE_PIG_HERD"] = "Disable\npig-herd",
    ["LABEL_DISABLE_COUNT"] = "Disable\nThe Count",

      --tooltips

    ["TOOLTIP_DISABLE_FEATURE"] = "It will no longer be allowed to place a follower on a {s1}",
    ["TOOLTIP_NERF_SMALL_CITIES"] = "Changes scoring so that completed cities containing only 2 tiles are worth only 2 points. This is the same as the original Carcassonne release.",
    ["TOOLTIP_REDUCE_TOWER_RANGE"] = "If checked, the tower range will start with just the tile it is placed on, and increase from there.",
    ["TOOLTIP_RIVER_MIX_TILES"] = "If checked, all river tiles, including end pieces, will be mixed.",
    ["TOOLTIP_RIVER_ALLOW_U_TURNS"] = "If checked, river tiles can be placed such that they loop back next to themselves. This can potentially lead to placement issues. Use at your own risk.",
    ["TOOLTIP_RIVER_ALLOW_UNCONNECTED"] = "If checked, river tiles no longer need to be placed such that they continue a previously started river.",
    ["TOOLTIP_DISABLE_PIG_HERD"] = "If checked, this will disable the pig-herd, which gives an extra point per city to farmers.",
    ["TOOLTIP_DISABLE_COUNT"] = "If checked, this will disable the Count.",

    --Game Messages

      --AI

    ["MESSAGE_AI_CALCULATING"] = "AI player is calculating their move...",
    ["MESSAGE_AI_SKIPPING_FIGURE"] = "AI decided not to place a figure.",
    ["MESSAGE_AI_RECALCULATING_ODDS"] = "WARNING: The number of tiles in the stack is different than expected. This can happen if someone draws a tiles out of turn. Re-calculating odds...",
    ["MESSAGE_AI_FINISHED_RECALCULATING_ODDS"] = "Finished re-calculating odds. AI will now calculate a move.",
    ["MESSAGE_AI_GAME_OVER"] = "AI could not find the tile stack. The game is assumed to be over.",
    ["MESSAGE_AI_NO_LOCATION"] = "AI could not find a location for the tile. It will be reshuffled into the tile stack, and a new tile drawn.",
    ["MESSAGE_AI_ERROR_NO_TILESTACK"] = "ERROR: Cannot return this tile to the tilestack. If this tile is part of a river, you will need to manually shuffle it back in and skip back to this AI player. If this tile is the last tile in the game, you should discard it and end the game. Otherwise, there may be an issue, in which case discard the tile and skip the turn. If all else fails, restart the game.",

      --Feature Map Management

    ["MESSAGE_PLAY_AREA_SHIFTING"] = "Play area is being shifted to make room for more tiles.",

      --Global

    ["MESSAGE_LAKE_TILE_BONUS_TURN"] = "{p1} gets another turn for laying down the volcano lake tile.",
    ["MESSAGE_WHEEL_FORTUNE"] = "The pig landed on the Fortune event. The current player will be awarded 3 points.",
    ["MESSAGE_WHEEL_FORTUNE_SCORED"] = "{p1} scores 3 points for landing on the Fortune event.",
    ["MESSAGE_WHEEL_EVENT_DISABLED"] = "The {s1} event is currently disabled. Nothing happens.",
    ["MESSAGE_WHEEL_TAXES"] = "The pig landed on the Taxes event. Each knight will score 1 point for every knight (included itself) and pennant in their city.",
    ["MESSAGE_WHEEL_EVENT_SCORED"] = "{p1} scores {n1} points for the {s1} event.",
    ["MESSAGE_WHEEL_FAMINE"] = "The pig landed on the Famine event. Each farmer will score 1 point per completed city touching their field (bonuses count).",
    ["MESSAGE_WHEEL_STORM"] = "The pig landed on the Storm event. Every player will be awarded 1 point for each unused follower in their supply.",
    ["MESSAGE_WHEEL_INQUISITION"] = "The pig landed on the Inquisition event. Every player will receive 2 points per monk.",
    ["MESSAGE_WHEEL_INQUISITION_SCORED"] = "{p1}'s follower scores {n1} points for the {s1} event.",
    ["MESSAGE_WHEEL_PLAGUE"] = "The pig landed on the Plague event. Each player must return 1 follower from a land tile.",
    ["MESSAGE_WHEEL_PLAGUE_PLAYER_SKIPPED"] = "{p1} did not have any followers in play for the Plague event and was skipped.",
    ["MESSAGE_WHEEL_PLAGUE_FOLLOWER_AUTOMATICALLY_REMOVED"] = "{p1} only had 1 follower in play for the Plague event. It was removed.",
    ["MESSAGE_WHEEL_PLAGUE_PROMPT"] = "{p1} must choose a follower to remove for the Plague event.",
    ["MESSAGE_WHEEL_PLAGUE_REMOVAL"] = "{c1} {f1} was chosen to be removed by the plague.",
    ["MESSAGE_WHEEL_CROWN_SCORED"] = "{p1}'s follower scores {n1} points on the {s1} Crown.",
    ["MESSAGE_DRAGON_AWAKENED"] = "The dragon has awakened!",
    ["MESSAGE_DRAGON_MOVING"] = "The dragon is on the move!",
    ["MESSAGE_DRAGON_TILE_DRAWN_BEFORE_AWAKENED"] = "Dragon tile drawn, but the dragon has not yet awaken. According to the rules, the tile should be placed back in the stack, shuffled, and a new tile drawn. It is not enforced by the script, though.",
    ["MESSAGE_DRAGON_TILE_PLAYED_BEFORE_AWAKENED"] = "Dragon tile played, but the dragon has not yet awaken.",
    ["MESSAGE_DRAGON_MOVES_REMAINING"] = "Dragon moves remaining: {n1}. {p1}'s turn to move.",
    ["MESSAGE_DRAGON_STUCK"] = "Dragon has no valid places to move to. Ending dragon movement.",
    --{n1} is the number of figures. {f1} is the name of the figure. ie. "5 sheep have been eaten..."
    ["MESSAGE_DRAGON_SHEEP_EAT_MESSAGE"] = "{n1} {f1} have been eaten by the dragon! Om nom nom!",
    --{c1} is the description of the figure (ie. Red). {f1} is the name of the figure. ie. "Red Follower has been eaten..."
    ["MESSAGE_DRAGON_FIGURE_EAT_MESSAGE"] = "{c1} {f1} has been eaten by the dragon! Om nom nom!",
    ["MESSAGE_DRAGON_COC_PROTECTION"] = "{c1} {f1} is protected from the dragon in the City of Carcassonne.",
    ["MESSAGE_SKIP_FAIRY_CONFIRMATION"] = "You currently have the option to move the fairy. Are you sure you want to skip? Click again to confirm.",
    ["MESSAGE_ROBBER_BARON_AWARD"] = "{p1} has been awarded the Robber Baron for completing the longest road ({n1} tiles).",
    ["MESSAGE_KING_AWARD"] = "{p1} has been awarded the King for completing the biggest city ({n1} tiles)",
    ["MESSAGE_TRADE_TOKEN_AWARD"] = "{p1} has been awarded a {s1} for completing the city.",
    ["MESSAGE_PRINCESS_SEDUCTION_WAGON"] = "{c1} {f1} has been seduced by the princess! Well not the wagon but the wagon crew... all of them... wow. Let's move on and forget this.",
    ["MESSAGE_PRINCESS_SEDUCTION"] = "{c1} {f1} has been seduced by the princess! bow chicka wow wow~",
    ["MESSAGE_ABBOT_RETRIEVE"] = "{p1} retrieves their abbot back for {n1} points on {s1}",
    ["MESSAGE_TOWER_CAPTURE"] = "{c1} {f1} has been captured by {p1}",
    ["MESSAGE_TOWER_SELF_CAPTURE"] = "{c1} {f1} was captured by its owner and returned to supply.",
    ["MESSAGE_TOWER_RANSOM"] = "{c1} {f1} was ransomed from {c2} for 3 points and returned to supply.",
    ["MESSAGE_TOWER_EXCHANGE_FOLLOWER"] = "{p1} and {p2} return each others' followers",
    ["MESSAGE_TOWER_EXCHANGE_PROMPT"] = "{p1} must choose a prisoner from {p2} to exchange for",
    ["MESSAGE_TOWER_EXCHANGE"] = "{c1} {f1} was returned to its owner in exchange for a prisoner.",
    ["MESSAGE_DEPENDENT_FIGURE_REMOVED"] = "{p1} no longer has a follower for their {f1} and must be removed.",
    ["MESSAGE_SHEPHERD_PROMPT"] = "{p1} added to their Shepherd's field and has an opportunity to expand their flock.",
    ["MESSAGE_SHEPHERD_FIELD_FULL"] = "No more room on field! Placing sheep on shepherd.",
    ["MESSAGE_SCORE_SHEPHERD"] = "{p1}'s Shepherd scores {n1} points for {n1} sheep.",
    ["MESSAGE_SHEPHERD_WOLF"] = "{p1}'s Shepherd loses all of its sheep to a wolf. No points scored.",
    ["MESSAGE_FLIER_LANDED_ON_DRAGON"] = "The follower flew directly into the dragon's mouth! The dragon thanks you for the delicious aerial food delivery.",
    ["MESSAGE_FLIER_NO_DESTINATION"] = "The destination tile has no valid incomplete features that this follower can land on. Returning follower.",
    ["MESSAGE_FLIER_NO_TILE"] = "No tile exists at flier destination. Returning follower.",
    ["MESSAGE_COC_FROM_CITY_PROMPT"] = "{p1} has a follower in the City of Carcassonne that can be moved to a completed feature.",
    ["MESSAGE_COC_FROM_CITY_GAMEOVER_PROMPT"] = "{p1} has a follower in the City of Carcassonne that can be moved to an incomplete feature.",
    ["MESSAGE_SHRINE_LOSE"] = "{c1} {f1} has lost the Cloister/Shrine challenge.",
    ["MESSAGE_SCORE"] = "{p1} scores {n1} points on {f1}.",
    ["MESSAGE_SCORE_TRADE_TOKENS"] = "{p1} scores {n1} points for possessing the most {f1}s.",
    ["MESSAGE_SCORE_KING_OR_ROBBER_BARON"] = "{p1} scores {n1} points for possessing the {f1}.",
    ["MESSAGE_SCORE_MAYOR_NO_POINTS"] = "{p1} scores 0 points on {f1}. A mayor can only score points if the city contains a Pennant!",
    ["MESSAGE_SCORE_FAIRY_IDLE"] = "{p1} scores 1 point for having a {f1} next to the fairy on their turn.",
    ["MESSAGE_SCORE_FAIRY_FINISH"] = "{p1} scores 3 points for having a {f1} next to the fairy when scoring a feature.",
    ["MESSAGE_SCORE_GOLD_MINES"] = "{p1} scores {n1} points on {n2} gold bars ({n3} points each).",
    ["MESSAGE_GAME_OVER"] = "Game over.",
    ["MESSAGE_GAME_OVER_PROMOTE"] = "If you enjoyed the mod, please give it a like on the workshop. If you encountered any bugs, please upload a save file and describe it in the workshop comments.",
    ["MESSAGE_FAIRY_WARNING_NO_TILESTACK"] = "WARNING: No tile stack found. No points awarded for fairy. If you just placed the last tile, you can ignore this message.",
    ["MESSAGE_GOLD_MINES_GOLD_AWARDED"] = "{p1} was awarded a gold bar for having control over a finished feature.",
    ["MESSAGE_GOLD_MINES_TAKE_GOLD_PROMPT"] = "{p1} may choose a gold bar for having control over a finished feature.",
    ["MESSAGE_WAGON_PROMPT"] = "{p1}'s wagon has finished and may now be placed back on a connected feature.",
    ["MESSAGE_WAGON_NO_FEATURES"] = "{p1}'s wagon has finished, but there were no available features connected.",
    ["MESSAGE_COC_TO_CITY_PROMPT"] = "{p1}'s move scored points for others but not themself. They can now place a follower in the City of Carcassonne if they choose.",
    ["MESSAGE_COC_COUNT_PROMPT"] = "{p1} may now move the Count if they wish.",
    ["MESSAGE_NO_STARTING_TILESET"] = "Cannot start a game without a starting tileset.",
    ["MESSAGE_NO_TILES"] = "Cannot start a game without tiles.",
    ["MESSAGE_AI_INCOMPATIBLE_EXPANSIONS"] = "Cannot start an AI game with incompatible expansions: {s1}.",
    ["MESSAGE_HILL_WARNING_NO_TILESTACK"] = "Warning: Hill drawn but draw pile not found. This could be because the draw pile has only 1 tile left or none. If there is 1 tile left, it must be manually placed underneath the hill.",
    ["MESSAGE_SHEPHERD_ERROR_NO_SHEEP_BAG_RETURNING"] = "Error: Sheep bag is missing! The bag needs to remain out in order to return sheep tokens.",
    ["MESSAGE_SHEPHERD_ERROR_NO_SHEEP_BAG_DRAWING"] = "Error: Sheep bag is missing! The bag needs to remain out in order to draw sheep tokens.",
    ["MESSAGE_ROBBER_BARON_ERROR_MISSING"] = "Error: Robber Baron missing! The token needs to remain out in order to awarded.",
    ["MESSAGE_KING_ERROR_MISSING"] = "Error: King missing! The token needs to remain out in order to awarded.",
    ["MESSAGE_TRADE_TOKENS_ERROR_MISSING"] = "Error: {s1} pile missing! The pile needs to remain out in order to draw trade goods",
    ["MESSAGE_TOWER_ERROR_MISSING_CAPTURE"] = "ERROR: Could not find the captor of the prisoner.",

      --Hint Markers

    ["MESSAGE_HINTS_NO_TILE_LOCATION"] = "There is no valid location to put this tile. If the tile was drawn from the stack, put it back in and shuffle, then draw another.",
    ["MESSAGE_HINTS_STARTING_TILE"] = "You may place this starting tile anywhere. It is recommended to place it near the center of the table.",
    ["MESSAGE_HINTS_MAGIC_PORTAL_CALCULATING"] = "Calculating all possible magic portal locations. Hints may be delayed...",
    ["MESSAGE_HINTS_NO_FIGURE_LOCATION"] = "There is no valid location to put this figure. If no other figure is valid, you'll need to skip placing a figure.",
    ["MESSAGE_HINTS_TOWER_CALCULATING"] = "Calculating all possible tower locations. Hints may be delayed...",
    ["MESSAGE_HINTS_NO_FAIRY_LOCATION"] = "There is no valid location to put the fairy. The fairy can only be placed next to your own followers.",
    ["MESSAGE_HINTS_COC_CALCULATING"] = "Calculating all possible locations. Hints may be delayed...",

      --Move Validation

    ["MESSAGE_FLIER_PLACED"] = "{c1} {f1} placed on a flier.",
    ["MESSAGE_TOWER_PLACED"] = "Tower started on a Tower Foundation.",
    ["MESSAGE_TOWER_INCREASED"] = "The tower has been increased by one level.",
    ["MESSAGE_FIGURE_PLACED"] = "{c1} {f1} placed on {s2}.",
    ["MESSAGE_SHRINE_CHALLENGED"] = "{c1} {f1} on {s2} has been challenged!",
    ["MESSAGE_COUNT_PLACED"] = "{f1} placed on {s2}.",
    ["MESSAGE_INVALID_LOCATION_FAIRY"] = "Invalid Location: Fairy must be placed on a tile containing a follower owned by you.",
    --This error is printed when you try to put a figure in the middle of a split feature, like the field on the left side of this tile: https://s20.postimg.cc/lusnmnm3x/Hills_Sheep_Weird_Cities3.png
    ["MESSAGE_INVALID_LOCATION_MIDDLE"] = "Invalid Location: The middle of this side is not valid. You must put the figure on one side of the feature or the other.",
    ["MESSAGE_FIGURE_PLACED_BEFORE_TILE"] = "You must place a tile before placing a figure.",
    --After dropping a figure there is a short delay. If someone changes their mind and picks up the figure again before the end of the delay, this message is printed.
    ["MESSAGE_FIGURE_PICKED_UP"] = "Figure picked up before validation. Please replace figure.",
    ["MESSAGE_WAGON_ILLEGAL_FIGURE"] = "You are only allowed to place the wagon at this time.",
    --This error is printed when you try to put a figure in the middle of a split feature, like the field on the left side of this tile: https://s20.postimg.cc/lusnmnm3x/Hills_Sheep_Weird_Cities3.png
    ["MESSAGE_INVALID_LOCATION_FLIER_MIDDLE"] = "Invalid Location: You must put the flier on one side of the feature or the other.",
    --ie. if someone rolls a 3 they must put the flier on the tile 3 spaces in that direction. If they try to place on another this message is printed
    ["MESSAGE_INVALID_LOCATION_FLIER_WRONG_TILE"] = "Invalid Location: You must place the figure on the tile corresponding to the flier dice roll.",
    ["MESSAGE_FLIER_WRONG_FIGURE"] = "Can only place the follower that was used on the flier.",
    ["MESSAGE_ERROR_NO_SCRIPT_DATA"] = "Error: This tile has no script data. Most likely this expansion hasn't yet been implemented.",
    ["MESSAGE_INVALID_LOCATION_TILE_NOT_ALIGNED"] = "Invalid Location: Tile not aligned with the grid.",
    --After dropping a tile there is a short delay. If someone changes their mind and picks up the tile again before the end of the delay, this message is printed.
    ["MESSAGE_TILE_PICKED_UP"] = "Tile picked up before validation. Please replace tile.",
    ["MESSAGE_INVALID_LOCATION_ABBEY"] = "Invalid Location: Abbey must be surrounded by tiles on all 4 sides.",
    ["MESSAGE_INVALID_LOCATION_SHRINE_CLOISTER"] = "Invalid Location: Cannot place a tile such that more than one cloister is next to a shrine or vice versa.",
    ["MESSAGE_INVALID_LOCATION_RIVER_U_TURN"] = "Invalid Location: U-turns are not allowed on rivers.",
    ["MESSAGE_INVALID_LOCATION_RIVER_UNCONNECTED"] = "Invalid Location: Tile must continue the already placed river.",
    ["MESSAGE_INVALID_LOCATION_TILE_FEATURES_DONT_MATCH"] = "Invalid Location: Adjacent tiles do not match.",
    ["MESSAGE_INVALID_LOCATION_TILE_OUT_OF_BOUNDS"] = "Invalid Location: Tile must be placed in the blue play area.",
    ["MESSAGE_INVALID_LOCATION_TILE_NOT_ADJACENT"] = "Invalid Location: Must be adjacent to at least one tile.",
    ["MESSAGE_INVALID_LOCATION_TILE_LOCATION_TAKEN"] = "Invalid Location: Space already occupied by another tile.",
    ["MESSAGE_INVALID_LOCATION_FIGURE_WRONG_TILE"] = "Invalid Location: You must place the figure on the tile you had just placed.",
    ["MESSAGE_INVALID_LOCATION_MAGIC_PORTAL_USAGE_EXCEEDED"] = "Invalid Location: Only one follower may use the magic portal per turn.",
    ["MESSAGE_INVALID_LOCATION_FIGURE_ON_DRAGON"] = "Invalid Location: Cannot place a figure on the tile containing the dragon.",
    ["MESSAGE_INVALID_LOCATION_FIGURE_ON_RIVER"] = "Invalid Location: You can't occupy a river.",
    ["MESSAGE_INVALID_LOCATION_COC_NOT_ALLOWED"] = "Invalid Location: You cannot place a figure in the City of Carcassonne at this stage in the game.",
    ["MESSAGE_INVALID_LOCATION_FLIER_USAGE_EXCEEDED"] = "Invalid Location: Only one follower may use the flier per turn.",
    ["MESSAGE_INVALID_LOCATION_FLIER_ILLEGAL_FIGURE"] = "Invalid Location: Only a follower can be placed on a flier. Valid followers: Follower, Big Follower, Wagon, Mayor, Phantom.",
    ["MESSAGE_INVALID_LOCATION_FLIER_DISABLED"] = "The Flier was disabled in the control panel. You may not place anything on the flier.",
    ["MESSAGE_INVALID_LOCATION_TOWER_ILLEGAL_FIGURE"] = "Invalid Location: Only towers can be placed on tower foundations. Only additional towers, normal followers, big followers, and phantoms can be placed on towers.",
    ["MESSAGE_INVALID_LOCATION_TOWER_ALREADY_OCCUPIED"] = "Invalid Location: This tower already has a follower on it.",
    ["MESSAGE_INVALID_LOCATION_TOWER_FIGURE_BEFORE_TOWER"] = "Invalid Location: Followers cannot be placed on tower foundations.",
    ["MESSAGE_INVALID_LOCATION_SHEPHERD"] = "Invalid Location: Shepherd can only be placed on fields.",
    ["MESSAGE_INVALID_LOCATION_ABBOT"] = "Invalid Location: An abbot can only be placed on a garden or cloister.",
    ["MESSAGE_INVALID_LOCATION_GARDEN"] = "Invalid Location: Only an abbot can be placed on a garden.",
    ["MESSAGE_INVALID_LOCATION_BUILDER"] = "Invalid Location: A builder can only be placed on roads and cities.",
    ["MESSAGE_INVALID_LOCATION_PIG"] = "Invalid Location: A pig can only be placed on fields.",
    ["MESSAGE_INVALID_LOCATION_MAYOR"] = "Invalid Location: A mayor can only occupy a city.",
    ["MESSAGE_INVALID_LOCATION_WAGON"] = "Invalid Location: A wagon cannot occupy a field.",
    ["MESSAGE_INVALID_LOCATION_FEATURE_DISABLED"] = "Invalid Location: {s1} are disabled via the house rules.",
    ["MESSAGE_INVALID_LOCATION_BARN"] = "Invalid Location: A barn can only be placed on a corner of fields.",
    ["MESSAGE_INVALID_LOCATION_MAGIC_PORTAL"] = "Invalid Location: You may not use the magic portal to place a follower on a completed feature.",
    ["MESSAGE_INVALID_LOCATION_BUILDER_NO_PARENT"] = "Invalid Location: A builder can only be placed on a road/city containing at least one of your followers.",
    ["MESSAGE_INVALID_LOCATION_PIG_NO_PARENT"] = "Invalid Location: A pig can only be placed on a field containing at least one of your followers.",
    ["MESSAGE_INVALID_LOCATION_FEATURE_ALREADY_OCCUPIED"] = "Invalid Location: Feature already occupied.",
    ["MESSAGE_INVALID_LOCATION_WAGON_NOT_CONNECTED"] = "Invalid Location: Not connected to the previous feature by road.",
    ["MESSAGE_INVALID_LOCATION_WAGON_ALREADY_COMPLETE"] = "Invalid Location: Feature already finished. You must place the wagon in an incomplete feature.",
    ["MESSAGE_INVALID_LOCATION_FLIER"] = "Invalid Location: A flier can only be placed on a city, road, or cloister.",
    ["MESSAGE_INVALID_LOCATION_FLIER_ALREADY_COMPLETE"] = "Invalid Location: You may only place the flier on an incomplete feature.",
    ["MESSAGE_INVALID_LOCATION_COC_ILLEGAL_FIGURE"] = "Invalid Location: Only a follower can be placed at this stage of the game. Valid followers: Follower, Big Follower, Wagon, Mayor, Phantom.",
    ["MESSAGE_INVALID_LOCATION_COC_NOT_A_QUARTER"] = "Invalid Location: The figure must be placed in one of four specific quarters within the city.",
    ["MESSAGE_INVALID_LOCATION_COC"] = "Invalid Location: A figure can only be placed within the City of Carcassonne at this stage of the game.",
    ["MESSAGE_INVALID_LOCATION_WHEEL_CROWN"] = "Invalid Location: Only normal followers, big followers, and phantoms can be placed on Crown spaces.",
    ["MESSAGE_INVALID_LOCATION_WHEEL_CROWN_DISABLED"] = "The Crown spaces were disabled in the control panel. You may not place anything on them.",
    ["MESSAGE_INVALID_LOCATION_COC_ABBOT"] = "Invalid Location: An abbot can only be placed in the Cathedral Quarter.",
    ["MESSAGE_INVALID_LOCATION_COC_MAYOR"] = "Invalid Location: A mayor can only be placed in the Castle Quarter.",
    ["MESSAGE_INVALID_LOCATION_COC_WAGON"] = "Invalid Location: A wagon cannot be placed in the Market Quarter.",
    ["MESSAGE_INVALID_LOCATION_COC_ROADS_DISABLED"] = "Invalid Location: Roads are currently disabled in the house rules. Cannot use the Blacksmith Quarter.",
    ["MESSAGE_INVALID_LOCATION_COC_CITIES_DISABLED"] = "Invalid Location: Cities are currently disabled in the house rules. Cannot use the Castle Quarter.",
    ["MESSAGE_INVALID_LOCATION_COC_FIELDS_DISABLED"] = "Invalid Location: Fields are currently disabled in the house rules. Cannot use the Market Quarter.",
    ["MESSAGE_INVALID_LOCATION_COC_CLOISTERS_DISABLED"] = "Invalid Location: Cloisters are currently disabled in the house rules. Cannot use the Cathedral Quarter.",
    ["MESSAGE_COC_FROM_CITY_ILLEGAL_FIGURE"] = "Only followers from the City of Carcassonne can be placed now.",
    ["MESSAGE_INVALID_LOCATION_COC_FROM_WRONG_QUARTER"] = "Invalid Location: This figure was in the {f1} Quarter and can only be placed on a completed {s1}.",
    ["MESSAGE_INVALID_LOCATION_COC_COMPLETED_ONLY"] = "Invalid Location: Followers from the City of Carcassonne can only be placed on completed features.",
    ["MESSAGE_INVALID_LOCATION_COC_END_GAME_INCOMPLETE_ONLY"] = "Invalid Location: Followers from the City of Carcassonne can only be placed on incomplete features at the end of the game.",
    ["MESSAGE_INVALID_LOCATION_COC_LAST_TILE_ONLY"] = "Invalid Location: Followers from the City of Carcassonne can only be placed on features that were completed with the last tile.",

      --Save Game

    ["MESSAGE_GAME_LOADED"] = "Game loaded. It is now {p1}'s turn on state: {s1}.",
    ["MESSAGE_GAME_LOADED_CONTROL"] = "{c1} is controlled by {p1}",
    ["MESSAGE_GAME_LOADED_REWIND_NOTIFICATION"] = "Please note that rewinds are only partially supported. You may need to clean some things up if the state was saved while the script was running.",

      --Setup Game

    ["MESSAGE_SETUP_GAME_ALREADY_STARTED"] = "Game has already started. Start a new game if you wish to change settings.",
    ["MESSAGE_SETUP_NO_CONTROL_PANEL_PERMISSIONS"] = "Only promoted players can use the control panel.",
    ["MESSAGE_SETUP_COLOR_SUBSTITUTION"] = "{c1} has substituted their color/faction for {c2}",
    ["MESSAGE_SETUP_MODEL_SUBSTITUTION"] = "{c1} has substituted their {f1} model for a custom one",
    ["MESSAGE_SETUP_RIVER_II_NOTIFICATION"] = "You are currently playing with the river. Please place a river tile, then you may add more to it. According to the rules, the fork should be the first tile placed, followed by the facedown tiles until they are gone, then the spring, and lastly the lake piece.",
    ["MESSAGE_SETUP_RIVER_NOTIFICATION"] = "You are currently playing with the river. Please place a river tile, then you may add more to it. According to the rules, the spring should be the first tile placed, followed by the facedown tiles until they are gone, and then the lake.",
    ["MESSAGE_SETUP_START"] = "Game started. Good luck!",
    ["MESSAGE_SETUP_FIRST_PLAYER"] = "{p1} was randomly chosen as the first player.",

      --State Machine

    ["MESSAGE_STATE_NEW_TURN"] = "-----------It is now {p1}'s turn-----------",
    ["MESSAGE_STATE_NEW_TURN_CONTROL"] = "-------{c1} is controlled by {p1}------",
    ["MESSAGE_STATE_NEW_TURN_PLAYER_MISSING"] = "{c1} no longer has a controlling player. Another player may sit at this position, or control can be given to another as a hotseat player or an AI. Otherwise, this player will need to be skipped.",
    ["MESSAGE_NO_GAME_BUTTON_PERMISSIONS"] = "Only promoted players can use this button",
    ["MESSAGE_NO_BUTTON_PERMISSIONS"] = "Only the current player or promoted players can use this button",
    ["MESSAGE_GOLD_MINES_PLACE_GOLD_PROMPT"] = "Choose a location to place the gold bar",
    ["MESSAGE_LAKE_PLACE_FERRY_PROMPT"] = "Choose a route for the ferry",
    ["MESSAGE_BUILDER_PROMPT"] = "{p1}'s builder has allowed them to draw another tile. Please do so, along with the usual actions, before ending your turn.",
    ["MESSAGE_GAME_LOADED_DURING_SCORING"] = "Loaded game was in the middle of scoring. Game pieces may need to be removed manually. Skipping to post scoring events. Some unscored pieces may remain.",
    ["MESSAGE_FIGURE_PROMPT"] = "Place a figure if desired.",
    ["MESSAGE_PHANTOM_PROMPT"] = "Place your phantom if desired.",
    ["MESSAGE_FLIER_DIE_PROMPT"] = "Roll the flier die to determine your flier's distance.",
    ["MESSAGE_FLIER_PROMPT"] = "Place the flier on the destination tile.",
    ["MESSAGE_ERROR_NO_ACTION_FOR_STATE"] = "Error: action - {s1} does not exist for current state - {s2}",
    ["MESSAGE_ERROR_NO_STATE"] = "Error: current state does not exist - {s1}",

      --TTS Events

    ["MESSAGE_HOTSEAT_TAKEN"] = "{p1}'s hotseat, {c1}, has been taken.",
    ["MESSAGE_HOTSEAT_OWNER_MOVED"] = "{c1}'s hotseat owner, {c2}, has left the table or moved.",
    ["MESSAGE_FLIER_DIE_ROLL"] = "{p1} rolled a {n1}",
    ["MESSAGE_FLIER_WRONG_PLAYER_ROLLED"] = "ERROR: It is not currently your turn OR you rolled the die without picking it up.",
    ["MESSAGE_TILE_NOT_ALLOWED"] = "It is currently not allowed to place a tile. You are only allowed to place a tile at the beginning of your turn. Current state: {s1}",
    ["MESSAGE_PHANTOM_NOT_ALLOWED"] = "It is currently not allowed to place a phantom. You are only allowed to place a phantom after placing a figure. Current state: {s1}",
    ["MESSAGE_TOWER_NOT_ALLOWED"] = "It is currently not allowed to place a tower. You are only allowed to place a tower after placing a tile. Current state: {s1}",
    ["MESSAGE_FIGURE_NOT_ALLOWED"] = "It is currently not allowed to place a figure. You are typically only allowed to place a figure after a tile. Current state: {s1}",
    ["MESSAGE_TOWER_WRONG_OWNER"] = "This tower doesn't belong to you. Make sure you check the color in the description.",
    ["MESSAGE_FIGURE_WRONG_OWNER"] = "Incorrect colored figure was dropped. Are you sure it is yours?",
    ["MESSAGE_FAIRY_NOT_ALLOWED"] = "It is currently not allowed to place the fairy. You are only allowed to place the fairy after placing a tile. Current state: {s1}",
    ["MESSAGE_COUNT_NOT_ALLOWED"] = "It is currently not allowed to place the count. You are only allowed to move the count after placing a follower in the City of Carcassonne. Current state: {s1}",
    ["MESSAGE_DROP_SPAM"] = "Multiple pieces dropped too fast, please wait.",
    ["MESSAGE_DROP_WRONG_PLAYER"] = "It is currently not your turn. Dropped pieces will not count.",
    ["MESSAGE_DROP_GAME_NOT_STARTED"] = "Game over or not yet started. Press the start game button and re-lay tile.",
    ["MESSAGE_TILE_REMOVED"] = "Tile removed from grid.",
  },
  ['nl-NL'] = {
    ["AI/Hotseat (H)"] = "AI/Meespeler (H)",
    --Player Colors
    ["Green"] = "Groen",
    ["Purple"] = "Paars",
    ["White"] = "Wit",
    ["Blue"] = "Blauw",
    ["Red"] = "Rood",
    ["Pink"] = "Roze",
    ["Magenta"] = "Magenta",
    ["Yellow"] = "Geel",
    ["Orange"] = "Oranje",
    ["Cyan"] = "Cyaan",
    ["Teal"] = "Taup",
    ["Grey"] = "Grijs",
    ["Black"] = "Zwart",
    ["Brown"] = "Bruin",
    ["Amber"] = "Amber",
    ["Rose"] = "Oud-roze",
    ["Vermilion"] = "Vermiljoen",
    ["Chartreuse"] = "Lichtgroen",
    --AI Difficulties
    ["Easy"] = "Makkelijk",
    ["Hard (Beta)"] = "Moeilijk (beta)",
    --Figure Names
    ["Follower"] = "Meeple", --"隨從",
    ["Followers"] = "Meeples",
    ["Big Follower"] = "Grote Meeple", --"大隨從",
    ["Builder"] = "Bouwmeester",
    ["Pig"] = "Varken",
    ["Mayor"] = "Burgemeester",
    ["Wagon"] = "Transportwagen",
    ["Barn"] = "Herenboerderij",
    ["Shepherd"] = "Herder",
    ["Messenger"] = "Boodschapper",
    ["Mage"] = "Tovenaar",
    ["Mages"] = "Tovenaars", --TEMP: for model substitution
    ["Witch"] = "Heks",
    ["Witches"] = "Heksen", --TEMP: for model substitution
    ["Robber"] = "Rover", -- From mini-expansion: The Robbers
    ["Robbers"] = "Rovers", -- From mini-expansion: The Robbers
    --Situational Figure Names
    ["Meeple"] = "Meeple", --one of the 7 basic followers
    ["Farmer"] = "Boer", --follower in a field
    ["Knight"] = "Ridder", --follower in a city
    --["Robber"] = "Struikrover", --follower on a road - Shared with Robber name from The Robber
    ["Monk"] = "Monnik", --follower in a cloister
    --Neutral Figure Names
    ["Dragon"] = "Draak",
    ["Fairy"] = "Fee",
    ["Count"] = "Graaf",
    ["Tower"] = "Toren",
    ["Towers"] = "Torens",
    ["Bridge"] = "Brug",
    ["Bridges"] = "Bruggen",
    ["Castle"] = "Kasteel",
    ["Castles"] = "Kastelen",
    ["Gold Bar"] = "Goudstaaf",
    --Feature Names
    ["Field"] = "Weide",
    ["Fields"] = "Weides",
    ["City"] = "Stad",
    ["Cities"] = "Steden",
    ["Road"] = "Weg",
    ["Roads"] = "Wegen",
    ["Cloister"] = "Klooster",
    ["Cloisters"] = "Kloosters",
    --Situational Feature Names
    ["Farm"] = "Boerderij", --field with a follower on it
    ["Farms"] = "Boerderijen", --field with a follower on it
    --Special Feature Names
    ["Cathedral"] = "Kathedraal",
    ["Cathedrals"] = "Kathedralen",
    ["Inn"] = "Herberg",
    ["Inns"] = "Herbergen",
    ["Princess"] = "Jonkvrouw",
    ["Volcano"] = "Vulkaan",
    ["Portal"] = "Poort", --from big box 3 manual (bad translation?)
    ["Portals"] = "Poorten",
    ["Tower Foundation"] = "Torenbouwplaats",
    ["Abbey"] = "Abdij",
    ["Shrine"] = "Cultusplaats",
    ["Shrines"] = "Cultusplaatsen",
    ["Hill"] = "Heuvel",
    ["Hills"] = "Heuvels",
    ["Vineyard"] = "Wijngaard",
    ["Vineyards"] = "Wijngaarden",
    ["Bazaar"] = "Bazaar",
    ["Bazaars"] = "Bazaars",
    ["Fliers"] = "Vliegtuigen",
    ["Messages"] = "Nieuwsberichten",
    ["Ferries"] = "Veerboten",
    ["Gold"] = "Goud", --Should the special feature just be called gold bars?
    --City of Carcassonne Quarters
    ["Castle Quarter"] = "Kasteel",
    ["Blacksmith Quarter"] = "Smederij",
    ["Cathedral Quarter"] = "Kathedraal",
    ["Market Quarter"] = "Markt",
    --Wheel of Fortune Features
    ["Crown"] = "Kroon",
    ["Fortune"] = "Fortuin",
    ["Taxes"] = "Belasting",
    ["Famine"] = "Hongersnood",
    ["Storm"] = "Storm",
    ["Inquisition"] = "Inquisitie",
    ["Plague"] = "Pest",
    --["Dragon"] = "火龍", --shared with figure name
    --Token Names
    ["Trade Goods"] = "Handelswaren",
    ["Wine Token"] = "Wijnfiche",
    ["Cloth Token"] = "Lakenfiche",
    ["Wheat Token"] = "Graanfiche",
    --currently excluding the token name for display in the control panel
    ["King"] = "Koning",
    ["Robber Baron"] = "Rover", --currently shared with follower on a road. Consider renaming to Robber Baron later and possibly having a unique translation
    ["Knock Out"] = "Taartgevecht",
    ["Seduction"] = "Verliefd",
    ["Target"] = "Schietwedstrijd",
    ["Catch"] = "Vangen",
    --Starting Tiles
    ["Starting Tiles"] = "Starttegels",
    ["Base Starting Tile"] = "Standaard starttegel",
    ["The River"] = "De Rivier",
    ["The River II"] = "De Rivier II",
    ["The River (Big Box 5)"] = "De Rivier (Big Box 3)",
    ["City of Carcassonne"] = "De stad Carcassonne",
    ["School"] = "School",
    ["Wind Roses"] = "Windvaan",
    ["Wheel of Fortune"] = "Rad van Fortuin",
    --Expansion Names
    ["Inns & Cathedrals"] = "Kathedralen & Herbergen",
    ["Traders & Builders"] = "Kooplieden & Bouwmeesters",
    ["The Princess & The Dragon"] = "De Draak, de Fee & de Jonkvrouw",
    ["The Tower"] = "De Toren",
    ["Abbey & Mayor"] = "Burgemeesters & Abdijen",
    ["The Catapult"] = "De Katapult",
    ["Bridges, Castles, & Bazaars"] = "Bruggen, Burchten & Bazaars",
    ["Hills & Sheep"] = "Schapen & Heuvels",
    ["Count, King, & Robber"] = "Graaf, Koning & Consorten",
    ["King & Robber Baron"] = "Koning & Roofridder", --aka King & Scout, both unused.
    ["The Cathars"] = "De Katharen", --Never released in Dutch
    ["The Count of Carcassonne"] = "De Graaf",
    ["The Cult, The Siege"] = "Cultusplaatsen en Ketters", --??
    ["The Phantom"] = "De Volgeling",
    ["The Festival"] = "Het Feest",
    ["The Flier"] = "De Vliegtuigen",
    ["The Messages"] = "Nieuwsberichten",
    ["The Ferries"] = "De Veerboten",
    ["The Goldmines"] = "De Goudmijnen",
    ["Mage & Witch"] = "Tovenaar & Heks",
    ["The Robbers"] = "De Rovers",
    ["Wheel of Fortune"] = "Rad van Fortuin", --Shared with starting tile name
    ["Crop Circles I"] = "Graancirkels I",
    ["Crop Circles II"] = "Graancirkels II",
    ["The Plague"] = "De Pest",
    ["The Tunnel"] = "De Tunnel",
    --got many of the following from https://www.bger.org/thread-20997-1-1.html
    ["Little Buildings"] = "Kleine Gebouwen", --Unknown in Dutch
    ["We Go to Carcassonne"] = "We gaan naar Carcassonne",
    ["The Besiegers"] = "De Belegeraars", --Not released in Dutch
    ["The German Monasteries"] = "De Duitse Kloosters",
    ["The Abbot"] = "De Abt",
    ["Halflings I"] = "De Halflingen I",
    ["Halflings II"] = "De Halflingen II",
    ["Darmstadt"] = "Darmstadt",
    ["Spiel Promo"] = "Spiel Promo",
    ["Castles in Germany"] = "Kastelen",
    ['City Gates'] = "De Stadspoort", --Die Stadttore in German. I believe this is a fan expansion.
    --Marker Types
    ["Both"] = "Beide",
    ["None"] = "Geen",
    ["Scoring"] = "Punten",
    ["Hints"] = "Hints",

    --Button Labels

    ["BUTTON_LABEL_START_GAME"] = "Spel\nstarten",
    ["BUTTON_LABEL_END_GAME"] = "Einde spel\n(punten\ntellen)",
    ["BUTTON_LABEL_SCORE_SUMMARY"] = "Punten\nSamenvatting",
    ["BUTTON_LABEL_SKIP_TURN"] = "Beurt\nOverslaan",
    ["BUTTON_LABEL_MARKERS"] = "Tekens\ntonen:\n",
    ["BUTTON_LABEL_PROMPT_PLACE_FIGURE"] = "Speelstuk zetten\nOF",
    ["BUTTON_LABEL_SKIP_PLACING_FIGURE"] = "Geen speelstuk\nzetten",
    ["BUTTON_LABEL_PLACE_GOLD"] = "Goud\nleggen",
    ["BUTTON_LABEL_SEDUCE_KNIGHT"] = "Ridder\nverleiden",
    ["BUTTON_LABEL_RETRIEVE_ABBOT"] = "Abt\nophalen",
    ["BUTTON_LABEL_PROMPT_PLACE_PHANTOM"] = "Volgeling zetten\nOF",
    ["BUTTON_LABEL_SKIP_PHANTOM"] = "Geen volgeling\nzetten",
    ["BUTTON_LABEL_SKIP_TOWER_CAPTURE"] = "Meeple niet\ngevangen nemen",
    ["BUTTON_LABEL_PROMPT_REPLACE_WAGON"] = "Transportwagen verzetten\nOF",
    ["BUTTON_LABEL_SKIP_WAGON"] = "Transportwagen niet\nverzetten",
    ["BUTTON_LABEL_PROMPT_COC"] = "Speelstuk in de stad\nCarcassonne zetten\nOF",
    ["BUTTON_LABEL_PROMPT_MOVE_COUNT"] = "De graaf naar een\nandere stadswijk verzetten\nOF",
    ["BUTTON_LABEL_SKIP_COUNT"] = "De graaf\nniet verzetten",
    ["BUTTON_LABEL_RETURN_FOLLOWER"] = "Meeple\nretourneren",
    ["BUTTON_LABEL_CAPTURE"] = "{f1}\ngevangen nemen",
    ["BUTTON_LABEL_RANSOM"] = "{f1}\nvrijkopen",
    ["BUTTON_LABEL_RETURN"] = "{f1}\nretourneren",
    ["BUTTON_LABEL_EXPAND_FLOCK"] = "Kudde\nuitbreiden",
    ["BUTTON_LABEL_HERD_FLOCK"] = "Kudde naar de\nstal drijven",
    ["BUTTON_LABEL_TAKE_GOLD"] = "Goudstaaf\nnemen",

    --UI Labels

    ["UI_AI_CALCULATING"] = "AI berekent zet...",

    --Control Panel Global

    ["LABEL_TILES"] = "Tegel(s)",
    ["LABEL_PREVIOUS_PAGE"] = "Vorige pagina",
    ["LABEL_NEXT_PAGE"] = "Volgende pagina",
    ["TOOLTIP_ENABLE_ALL"] = "Alle inschakelen",
    ["TOOLTIP_NUM_TILES"] = "{n1} tegel(s)",

    --Control Panel pg. 1

      --tooltips

    ["TOOLTIP_AI_HOTSEAT_TOGGLE"] = "Klik om te wisselen tussen:\nAI (makkelijk)\nAI (moeilijk)\nMedespeler (bij de speler die klikt)\nGeen",
    ["TOOLTIP_BASE_STARTING_TILE"] = "Gewone starttegel.",
    ["TOOLTIP_RIVER"] = "12 riviertegels waarmee een kronkelende rivieer gemaakt kan worden.",
    ["TOOLTIP_RIVER_II"] = "12 riviertegels met een splitsing die de rivier in 3 delen verdeelt, en een kudde varkens voor extra punten voor boeren.",
    ["TOOLTIP_RIVER_BB5"] = "12 riviertegels met extra permaente schapen voor herders.",
    ["TOOLTIP_CITY_OF_CARCASSONNE"] = "De starttegels De Stad Carcassonne. Telkens als je een tegel legt waardoor alleen anderen punten krijgt, mag je hier een meeple zetten. Deze meeples kunnen op andere projecten gezet worden nadat die zijn afgebouwd, maar voordat de punten zijn geteld.",
    ["TOOLTIP_WHEEL_OF_FORTUNE"] = "Trek tegels om het rad van fortuin te laten draaien als extra kanselement.",

      --messages

    ["MESSAGE_SEAT_OCCUPIED"] = "Hier zit al een speler. Kan hier geen medespeler maken.",
    ["MESSAGE_SEAT_ASSIGNED_TO_AI"] = "{c1} is nu een AI-speler met moeilijkheidsgraad: {s1}",
    ["MESSAGE_SEAT_ASSIGNED_TO_HOTSEAT"] = "{c1} is nu een medespeler van {p1}",
    ["MESSAGE_BASE_STARTING_TILE_NOT_ALLOWED"] = "Je kunt de gewone starttegel niet gebruiken als andere starttegels geselecteerd zijn.",
    ["MESSAGE_BASE_STARTING_TILE_REMOVED"] = "De gewone starttegel kan niet in combinatie met deze starttegelset gebruikt worden en wordt dus uitgeschakeld.",
    ["MESSAGE_HOTSEAT_REMOVED"] = "{c1} is niet langer een medespeler",
    ["MESSAGE_TOWER_COUNT_CHANGED"] = "Waarschuwing: aantal torendelen is nu {n1} door toevoegen/verwijderen mede- of AI-speler.",

    --Control Panel pg. 2

      --labels

    ["LABEL_BASE_GAME"] = "Basisspel",
    ["LABEL_MAJOR_EXPANSIONS"] = "Grote uitbreidingen",

      --tooltips

    ["TOOLTIP_FOLLOWER"] = "Meeple - De meeple is het standaard speelstuk van de speler. Deze kan op steden, wegen, weides of kloosters gezet worden om deze te bezetten.",
    ["TOOLTIP_BIG_FOLLOWER"] = "Grote meeple - De grote meeple telt voor 2 normale meeples. Dat betekent dat er maar 1 grote meeple voor nodig is om een project over te nemen van een speler met maar 1 normale meeple. Zelfs als de speler 2 normale meeples had, zouden de punten gedeeld worden.",
    ["TOOLTIP_INN"] = "Wegen met herbergen leveren dubbele punten op, maar alleen wanneer ze worden afgebouwd. Niet afgebouwd = 0 punten.",
    ["TOOLTIP_CATHEDRAL"] = "Afgebouwde steden met kathedralen krijgen 3 punten per tegen (i.p.v. 2), maar alleen als ze zijn afgebouwd. Niet afgebouwd = 0 punten."
    ["TOOLTIP_BUILDER"] = "Speciaal speelstuk - De bouwmeester kan op een weg of stad waar al een meeple staat gezet worden. Legt de eigenaar van de bouwmeester een tegel aan dit project aan, dan mag hij nog een tegel trekken.",
    ["TOOLTIP_PIG"] = "Speciaal speelstuk - Het varken kan op een weide waar tenminste 1 eigen boer ligt gezet worden. Aan het einde van het spel krijgt de speler met de meerderheid op de weide met een varken 4 punten per afgebouwde stad (i.p.v. 3).",
    ["TOOLTIP_TRADE_GOODS"] = "Op sommige stadstegels van Kooplieden & Bouwmeesters staan handelswarensymbolen. De speler die de stad afbouwt (ongeacht of die speler daar de macht had) krijgt voor elk symbool een handelswarenfiche. De speler die aan het einde van het spel de meeste fiches van een soort bezit krijgt 10 punten. Dit uitschakelen voorkomt niet dat de tegels met deze symbolen worden gebruikt, maar alleen dat de fiches worden uitgedeeld.",
    ["TOOLTIP_DRAGON"] = "Neutraal speelstuk - De Draak in het spel gebracht wanneer een tegel met een vulkaan wordt getrokken. Telkens als hierna een tegel met een draak getrokken wordt, wordt de draak door de spelers 6 keer verzet. De draak vreet bijna alle speelstukken van de tegel waar hij naartoe wordt verzet. Zie de regels voor meer informatie.",
    ["TOOLTIP_FAIRY"] = "Neutraal speelstuk - De fee kan verzet worden in plaats van het zetten van een meeple. De fee helpt op 3 manieren: geeft 1 punt aan de meeple waar ze naast staat bij het begin van de volgende beurt van die speler, geeft 3 punten extra wanneer het project met die meeple afgebouwd wordt en beschermd de tegel tegen de draak.",
    ["TOOLTIP_MAGIC_PORTAL"] = "Als een tegel met een magische poort wordt getrokken, mag de speler een meeple naar keuze op die tegel of een andere reeds gelegde tegel zetten. De normale regels voor het zetten van meeples blijven gelden.",
    ["TOOLTIP_PRINCESS"] = "Legt een speler een tegel met een stadsdeel met de jonkvrouw aan, dan mag hij in plaats van het zetten van een meeple 1 ridder (meeple) van stad af halen.",
    ["TOOLTIP_TOWER"] = "Een torendeel kan op een torenbouwplaats of bestaande toren gebouwd worden om meeples gevangen te nemen. Hoe hoger de toren, hoe groter het bereik.",

      --messages

    ["MESSAGE_FOLLOWER_COUNT_WARNING"] = "Waarschuwing: het is aan te raden het aantal gewone meeples op 7 te laten staan",
    ["MESSAGE_FOLLOWER_DISABLED_WARNING"] = "Waarschuwing: het is af te raden meeples uit te schakelen",
    ["MESSAGE_TOWER_COUNT_WARNING"] = "Waarschuwing: het is aan te raden het aantal torendelen standaard te laten",

    --Control Panel pg. 3

        --labels

    ["LABEL_ROBBER_BARON_SHORT_NAME"] = "Rover", -- This is the shortened form of "Robber Baron", since it doesn't fit on the control panel

      --tooltips

    ["TOOLTIP_ABBEY"] = "De Abdij is een speciale tegel die gebruikt kan worden in plaats van het trekken van een normale tegel van de stapel. De abdij kan alleen gelegd worden als deze aan alle 4 de zijden omgeven wordt door andere tegels. De abdij bouwt alle projecten (weg, stad, weide) af die ermee verbonden zijn. De abdij geldt als een klooster en er mag dus een meeple op gezet worden als monnik.",
    ["TOOLTIP_MAYOR"] = "Meeple - De Burgemeester kan alleen in een stad gezet worden. Zijn kracht is gelijk aan het aantal schilden in de stad.",
    ["TOOLTIP_WAGON"] = "Meeple - De Transportwagen kan alleen op een weg, stad, klooster of abdij worden gezet. De puntentelling is gelijk als bij een normale meeple, maar na de telling mag de transportwagen verzet worden naar een aangrenzend project. Een project is aangrenzend als het rechtstreeks verbonden is met een weg. Zie de regels voor meer informatie.",
    ["TOOLTIP_BARN"] = "Speciaal speelstuk - De Herenboerderij kan alleen op het kruispunt van 4 tegels gezet worden als alle aangrenzende landschappen weiden zijn. Voor alle meeples in deze weide worden de punten geteld en de meeple teruggegeven. Meeples op weiden die achteraf verbonden worden, worden ook verwijderd, maar tegen minder punten. Aan het einde van het spel levert de herenboerderij 4 punten per afgebouwde stad op. Zie de regels voor meer informatie.",
    ["TOOLTIP_KING"] = "De Koning gaat naar de speler die de grootste stad afbouwt (meeste tegels). Hij wordt verplaatst als iemand een grotere stad afbouwt. Aan het eind van het spel krijgt de speler met de Koning 1 punt per afgebouwde stad in het hele spel.",
    ["TOOLTIP_ROBBER_BARON"] = "De Roofridder gaat naar de speler die de langste weg afbouwt (meeste tegels). Hij wordt verplaatst als iemand een langere weg afbouwt. Aan het einde van het spel krijft de speler met de Roofridder 1 punt per afgebouwde weg in het hele spel.",
    ["TOOLTIP_SHRINE"] = "6 tegels met cultusplaatsen. Door een meeple op een cultusplaats te zetten naast een klooster, wordt het klooster uitgedaagd. Omgekeerd geldt hetzelfde. Het project wat het eerst wordt afgebouwd krijgt punten, het andere niet.",
    ["TOOLTIP_SHEPHERD"] = "Speciaal speelstuk: De Herder kan in een weide worden gezet. Na het zetten trekt de speler een schapenfiche en legt die op de weide. Telkens als de eigenaar van de herder een tegel aan de weide toevoegt, mag hij nog een fiche nemen of per schaap 1 punt tellen en de herder terugnemen. Trekt de speler een wolf, dan gaan de schapen verloren en neemt hij de herder terug. Zie de regels voor meer informatie.",
    ["TOOLTIP_HILL"] = "Trekt een speler een landtegel met een heuvel, dan wordt er een gedekte tegel onder geschoven. Zet de speler een meeple op een project op die tegel dan wordt een gelijke macht bij het punten tellen in zijn voordeel beslist. Zie de regels voor meer informatie. Uitschakelen voorkomt niet dat deze tegels meegenomen worden in de stapel of dat er gedekte tegels onder geschoven worden.",
    ["TOOLTIP_VINEYARD"] = "Op sommige tegels van Schapen & Heuvels staat een Wijngaard. Als een klooster wordt afgebouwd met aangrenzend één of meer van deze tegels krijgt de speler 3 punten extra per wijngaard. Als het klooster niet wordt afgebouwd, geven wijngaarden geen extra punten. Uitschakelen voorkomt niet dat deze tegels meegenomen worden in de stapel.",

      --messages

    ["MESSAGE_BASE_STARTING_TILE_NOT_COMPATIBLE_WITH_COC"] = "De gewone starttegel kan niet worden gecombineerd met de Stad Carassonne en wordt verwijderd.",

    --Control Panel pg. 4

      --labels

    ["LABEL_MINI_EXPANSIONS"] = "Mini-uitbreidingen",
    ["LABEL_WHEEL_SHORT_NAME"] = "Rad", -- This is the shortened form of "Wheel of Fortune", since it doesn't fit on the control panel
    ["LABEL_WHEEL_TILES"] = "Rad-tegels",

      --tooltips

    ["TOOLTIP_WHEEL_CROWN"] = "Spelers kunnen ervoor kiezen om een meeple op de kroon te zetten in plaats van op een tegel, dit levert punten op als er een varken op terecht komt.",
    ["TOOLTIP_WHEEL_FORTUNE"] = "Als het varken op Fortuin terecht komt, krijgt de huidige speler 3 punten.",
    ["TOOLTIP_WHEEL_TAX"] = "Als het varken op Belasting terecht komt, krijgt de speler 1 punt voor iedere ridder en ieder schild in die stad.",
    ["TOOLTIP_WHEEL_TILES"] = "19 tegels met Rad van Fortuin-symbool, waarmee het rad gaat draaien.",
    ["TOOLTIP_WHEEL_FAMINE"] = "Als het varken op Hongersnood terecht komt, krijgt elke boer 1 punt per afgebouwde stad in die weide.",
    ["TOOLTIP_WHEEL_STORM"] = "Als het varken op Storm terecht komt, krijgt elke speler 1 punt voor elke ongebruikte meeple in zijn voorraad.",
    ["TOOLTIP_WHEEL_INQUISITION"] = "Als het varken op Inquisitie terecht komt, krijgt elke speler 2 punten per monnik.",
    ["TOOLTIP_WHEEL_PLAGUE"] = "Als het varken op Pest terecht komt, moet elke speler 1 meeple uit het spel terug nemen in zijn voorraad.",
    ["TOOLTIP_FLIER"] = "Er mag een meeple op het Vliegtuig gezet worden. Als je dat doet, wordt er een dobbelsteen gegooid om te kijken hoe ver de meeple gaat vliegen. De speler moet de meeple dan, indien mogelijk, op die tegel zetten en kan die zelfs op een project zetten dat al bezet is (zelfs een klooster). Weides zijn niet toegestaan.",
    ["TOOLTIP_GOLD"] = "Op een tegel met een goudsymbool moet een goudstaaf gelegd worden evenals op een aangrenzende tegel. Wordt een project afgebouwd dat tegels omvat waar goudstaven op liggen, dan krijgt de speler die het project afgebouwd heeft die. De goudstaven leveren aan het einde van het spel punten op.",
    ["TOOLTIP_FERRY"] = "Op meren zijn veerboten actief die twee wegen met elkaar verbinden. De veerboten kunnen echter tijdens het spel wijzigen.",

      --messages

    ["MESSAGE_BASE_STARTING_TILE_NOT_COMPATIBLE_WITH_WOF"] = "De gewone starttegel kan niet gecombineerd worden met het Rad van Fortuin en wordt uitgeschakeld.",
    ["MESSAGE_WHEEL_DISABLED"] = "Deze optie kan niet ingeschakeld worden als het rad uitgeschakeld is.",

    --Control Panel pg. 5

      --labels

    ["LABEL_MICRO_EXPANSIONS"] = "Micro-uitbreidingen",

      --tooltips

    ["TOOLTIP_GAMES_QUARTERLY"] = "10 unieke tegels om aan de basisset toe te voegen plus een speciale brontegel voor rivier-sets die de weide scheidt met een weg.",
    ["TOOLTIP_PHANTOMS"] = "Een volgeling kan als tweede stuk na je normale speelstuk gezet worden.",
    ["TOOLTIP_SPIEL_PROMO"] = "Eén enkel stadsdeel. Verder niks.",
    ["TOOLTIP_WE_GO_TO_CARCASSONNE"] = "2 unieke tegels. Baba Yaga's hut lijkt op een klooster, maar de puntenwaarde begint bij 10 en daalt met 1 punt voor elke aangrenzende tegel. Bogatyr's Keuze is een viersprong waarvan er 3 doorlopen een een 4e op de kruising eindigt.",

    --Control Panel pg. 6

      --labels

    ["LABEL_HOUSE_RULES"] = "Huisregels",
    ["LABEL_DISABLE_FEATURE"] = "{s1} uitschakelen",
    ["LABEL_NERF_SMALL_CITIES"] = "Zwakke kleine steden",
    ["LABEL_REDUCE_TOWER_RANGE"] = "Torenbereik\nverkleinen",
    ["LABEL_RIVER_MIX_TILES"] = "Alle riviertegels\nmengen",
    ["LABEL_RIVER_ALLOW_U_TURNS"] = "U-bocht\ntoestaan",
    ["LABEL_RIVER_ALLOW_UNCONNECTED"] = "Onverbonden\ntoestaan",
    ["LABEL_DISABLE_PIG_HERD"] = "Varkenskudde\nuitschakelen",
    ["LABEL_DISABLE_COUNT"] = "De Graaf\nuitschakelen",

      --tooltips

    ["TOOLTIP_DISABLE_FEATURE"] = "Het is niet meer toegestaan een meeple op een {s1} te zetten",
    ["TOOLTIP_NERF_SMALL_CITIES"] = "Puntentelling aanpassen zodat steden die uit maar twee tegels bestaan nog maar 2 punten waard zijn. Zoals in het oorspronkelijke spel.",
    ["TOOLTIP_REDUCE_TOWER_RANGE"] = "Indien ingeschakeld begint het torenbereik met alleen de tegel waar hij op staat en wordt van daaruit uitgebreid.",
    ["TOOLTIP_RIVER_MIX_TILES"] = "Indien ingeschakeld worden alle riviertegels inclusief de eindstukken door elkaar gehusseld.",
    ["TOOLTIP_RIVER_ALLOW_U_TURNS"] = "Indien ingeschakeld kunnen riviertegels in een U-bocht gelegd worden. Dit kan tot problemen leiden. Gebruik op eigen risico.",
    ["TOOLTIP_RIVER_ALLOW_UNCONNECTED"] = "Indien ingeschakeld hoeven riviertegels niet zodanig gelegd te worden dat de rivier verlengd wordt.",
    ["TOOLTIP_DISABLE_PIG_HERD"] = "Indien ingeschakeld wordt de varkenskudde, die boeren een extra punt per stad geeft, uitgeschakeld.",
    ["TOOLTIP_DISABLE_COUNT"] = "Indien ingeschakeld, doet de Graaf niet mee.",

    --Game Messages

      --AI

    ["MESSAGE_AI_CALCULATING"] = "AI-speler berekent zijn zet...",
    ["MESSAGE_AI_SKIPPING_FIGURE"] = "AI heeft besloten geen speelstuk te zetten.",
    ["MESSAGE_AI_RECALCULATING_ODDS"] = "WAARSCHUWING: Het aantal tegels op de stapel wijkt af van het verwachtte aantal. Dit kan gebeuren als iemand buiten zijn beurt een tegel trekt. Kansen herberekenen...",
    ["MESSAGE_AI_FINISHED_RECALCULATING_ODDS"] = "Klaar met herberekenen kansen. AI berekent nu een zet.",
    ["MESSAGE_AI_GAME_OVER"] = "AI kan de tegelstapel niet vinden. Aangenomen wordt dat het spel voorbij is.",
    ["MESSAGE_AI_NO_LOCATION"] = "AI kon geen locatie vinden voor de tegel. De tegels worden opnieuw geschud en een nieuwe tegel getrokken.",
    ["MESSAGE_AI_ERROR_NO_TILESTACK"] = "FOUT: Kan deze tegel niet retourneren naar de tegelstapel. Als deze tegel onderdeel uitmaakt van een rivier, moet deze handmatig er terug in geschud worden en doorgeklikt worden naar deze AI-speler. Als dit de laatste tegel van het spel is, schuif hem dan terzijde en beëindig het spel. Anders is er mogelijk een probleem, probeer de tegel terzijde te schuiven en de beurt over te slaan. Of herstart het spel als alle andere oplossingen niet werken.",

      --Feature Map Management

    ["MESSAGE_PLAY_AREA_SHIFTING"] = "Speelgebied wordt verschoven om ruimte te maken voor meer tegels.",

      --Global

    ["MESSAGE_LAKE_TILE_BONUS_TURN"] = "{p1} krijgt een extra beurt vanwege het leggen van de tegel met het meer en de vulkaan.",
    ["MESSAGE_WHEEL_FORTUNE"] = "Het varken landde op Fortuin. De huidige speler krijgt 3 punten.",
    ["MESSAGE_WHEEL_FORTUNE_SCORED"] = "{p1} krijgt 3 punten vanwege terecht komen op Fortuin.",
    ["MESSAGE_WHEEL_EVENT_DISABLED"] = "{s1} is momenteel uitgeschakeld. Er gebeurt niets.",
    ["MESSAGE_WHEEL_TAXES"] = "Het varken landde op Belasting. Elke ridder krijgt 1 punt voor elke ridder (inclusief zichzelf) en elk schild in zijn stad.",
    ["MESSAGE_WHEEL_EVENT_SCORED"] = "{p1} krijgt {n1} punten voor {s1}.",
    ["MESSAGE_WHEEL_FAMINE"] = "Het varken landde op Hongersnood. Elke boer krijgt 1 punt per afgebouwde stad in zijn weide (+ bonussen).",
    ["MESSAGE_WHEEL_STORM"] = "Het varken landde op Storm. Elke speler krijgt 1 punt voor elke ongebruikte meeple in zijn voorraad.",
    ["MESSAGE_WHEEL_INQUISITION"] = "Het varken landde op Inquisitie. Elke speler krijgt 2 punten per monnik.",
    ["MESSAGE_WHEEL_INQUISITION_SCORED"] = "De meeple van {p1} krijgt {n1} punten voor {s1}.",
    ["MESSAGE_WHEEL_PLAGUE"] = "Het varken landde op Pest. Elke speler moet 1 meeple van een landtegel afhalen.",
    ["MESSAGE_WHEEL_PLAGUE_PLAYER_SKIPPED"] = "{p1} had geen meeples in het spel voor de Pest en is overgeslagen.",
    ["MESSAGE_WHEEL_PLAGUE_FOLLOWER_AUTOMATICALLY_REMOVED"] = "{p1} had slechts 1 meeple in het spel voor de Pest. Deze is verwijderd.",
    ["MESSAGE_WHEEL_PLAGUE_PROMPT"] = "{p1} moet een meeple kiezen die door de Pest wordt verwijderd.",
    ["MESSAGE_WHEEL_PLAGUE_REMOVAL"] = "{c1} kiest {f1} om verwijderd te worden door de pest.",
    ["MESSAGE_WHEEL_CROWN_SCORED"] = "De meeple van {p1} krijgt {n1} punten op de {s1} Kroon.",
    ["MESSAGE_DRAGON_AWAKENED"] = "De draak is ontwaakt!",
    ["MESSAGE_DRAGON_MOVING"] = "De draag gaat op jacht!",
    ["MESSAGE_DRAGON_TILE_DRAWN_BEFORE_AWAKENED"] = "Er is een draaktegel getrokken, maar de draag is nog niet ontwaakt. Volgens de regels moet de tegel teruggestopt worden in de stapel en opnieuw geschud worden om vervolgens een nieuwe tegel te trekken. Dit wordt echter niet door het script afgedwongen.",
    ["MESSAGE_DRAGON_TILE_PLAYED_BEFORE_AWAKENED"] = "Er is een draaktegel gespeeld, maar de draak is nog niet ontwaakt.",
    ["MESSAGE_DRAGON_MOVES_REMAINING"] = "Nog {n1} verplaatsingen van de draak over. Het is de beurt aan {p1} om de draak te verzetten.",
    ["MESSAGE_DRAGON_STUCK"] = "Er zijn geen geldige tegels meer waar de draak naartoe kan. De draak kan niet verder verzet worden.",
    --{n1} is the number of figures. {f1} is the name of the figure. ie. "5 sheep have been eaten..."
    ["MESSAGE_DRAGON_SHEEP_EAT_MESSAGE"] = "{n1} {f1} is/zijn door de draak opgevreten! Om nom nom!",
    --{c1} is the description of the figure (ie. Red). {f1} is the name of the figure. ie. "Red Follower has been eaten..."
    ["MESSAGE_DRAGON_FIGURE_EAT_MESSAGE"] = "{f1} van {c1} is door de draak opgevreten! Om nom nom!",
    ["MESSAGE_DRAGON_COC_PROTECTION"] = "{f1} van {c1} is in de Stad Carcassonne beschermd tegen de draak.",
    ["MESSAGE_SKIP_FAIRY_CONFIRMATION"] = "Je mag nu de fee verzetten. Weet je zeker dat je dit wilt overlaan? Klik nogmaals om te bevestigen.",
    ["MESSAGE_ROBBER_BARON_AWARD"] = "{p1} krijgt nu de Roofridder vanwege het afbouwen van de langste weg ({n1} tegels).",
    ["MESSAGE_KING_AWARD"] = "{p1} krijgt nu de Koning vanwege het afbouwen van de grootste stad ({n1} tegels)",
    ["MESSAGE_TRADE_TOKEN_AWARD"] = "{p1} heeft een {s1} gekregen voor het afbouwen van de stad.",
    ["MESSAGE_PRINCESS_SEDUCTION_WAGON"] = "{f1} van {c1} is verleid door de jonkvrouw! Nou ja, niet de transportwagen, maar de bemanning ervan... allemaal... wow. Laten we dit maar gauw vergeten en doorgaan.",
    ["MESSAGE_PRINCESS_SEDUCTION"] = "{f1} van {c1} is verleid door de jonkvrouw!",
    ["MESSAGE_ABBOT_RETRIEVE"] = "{p1} haalt zijn abt terug voor {n1} punten op {s1}",
    ["MESSAGE_TOWER_CAPTURE"] = "{f1} van {c1} is gevangen door {p1}",
    ["MESSAGE_TOWER_SELF_CAPTURE"] = "{f1} van {c1} is gevangen door de eigenaar en geretourneerd naar de voorraad.",
    ["MESSAGE_TOWER_RANSOM"] = "{f1} van {c1} is vrijgekocht van {c2} voor 3 punten en geretourneerd naar de voorraad.",
    ["MESSAGE_TOWER_EXCHANGE_FOLLOWER"] = "{p1} en {p2} geven elkaars meeples terug",
    ["MESSAGE_TOWER_EXCHANGE_PROMPT"] = "{p1} moet een gevangene kiezen van {p2} om uit te wisselen",
    ["MESSAGE_TOWER_EXCHANGE"] = "{f1} van is teruggegeven aan de eigenaar in ruil voor een gevangene.",
    ["MESSAGE_DEPENDENT_FIGURE_REMOVED"] = "{p1} heeft geen meeple meer voor {f1} en moet verwijderd worden.
    {p1} no longer has a follower for their {f1} and must be removed.",
    ["MESSAGE_SHEPHERD_PROMPT"] = "{p1} heeft de weide met zijn Herder uitgebreid en mag de kudde uitbreiden.",
    ["MESSAGE_SHEPHERD_FIELD_FULL"] = "Er is geen ruimte meer op de weide! De schapen worden op de herder gelegd.",
    ["MESSAGE_SCORE_SHEPHERD"] = "De Herder van {p1} levert {n1} punten op voor {n1} scha(a)p(en).",
    ["MESSAGE_SHEPHERD_WOLF"] = "De Herder van {p1} raakt al zijn schapen kwijt aan een wolf. Geen punten.",
    ["MESSAGE_FLIER_LANDED_ON_DRAGON"] = "De meeple vloog recht in de muil van de draak! De draak is dankbaar voor deze voedzame luchtpost.",
    ["MESSAGE_FLIER_NO_DESTINATION"] = "De doeltegel heeft geen geldige onafgebouwde projecten waar deze meeple op kan landen. Meeple wordt geretourneerd.",
    ["MESSAGE_FLIER_NO_TILE"] = "Er is geen tegel op de doellocatie. Meeple wordt geretourneerd.",
    ["MESSAGE_COC_FROM_CITY_PROMPT"] = "{p1} heeft een meeple in de Stad Carcassonne die verzet kan worden naar een afgebouwd project.",
    ["MESSAGE_COC_FROM_CITY_GAMEOVER_PROMPT"] = "{p1} heeft een meeple in de Stad Carcassonne die verzet kan worden naar een onafgebouwd project.",
    ["MESSAGE_SHRINE_LOSE"] = "{f1} van {c1} heeft de Klooster/Cultusplaats uitdaging verloren.",
    ["MESSAGE_SCORE"] = "{p1} krijgt {n1} punten voor {f1}.",
    ["MESSAGE_SCORE_TRADE_TOKENS"] = "{p1} krijgt {n1} punten voor de meeste {f1}s.",
    ["MESSAGE_SCORE_KING_OR_ROBBER_BARON"] = "{p1} krijgt {n1} punten voor de {f1}.",
    ["MESSAGE_SCORE_MAYOR_NO_POINTS"] = "{p1} krijgt 0 punten voor {f1}. Een burgemeester kan alleen punten krijgen als de stad een schild heeft!",
    ["MESSAGE_SCORE_FAIRY_IDLE"] = "{p1} krijgt 1 punt voor een {f1} naast de fee bij de volgende beurt.",
    ["MESSAGE_SCORE_FAIRY_FINISH"] = "{p1} krijgt 3 punten voor een {f1} naast de fee bij de puntentelling van een project.",
    ["MESSAGE_SCORE_GOLD_MINES"] = "{p1} krijgt {n1} punten voor {n2} goudsta(af)(ven) (elk {n3} punten).",
    ["MESSAGE_GAME_OVER"] = "Einde spel.",
    ["MESSAGE_GAME_OVER_PROMOTE"] = "Als je deze mod met plezier gespeeld hebt, geef die dan een 'like' in de 'Workshop'. Ben je tegen bugs aangelopen, upload dan een opgeslagen spel en beschrijf het probleem in het commentaar.",
    ["MESSAGE_FAIRY_WARNING_NO_TILESTACK"] = "WAARSCHUWING: Kan tegelstapel niet vinden. Geen punten toegekend voor de fee. Als je zojuist de laatste tegel gelegd hebt, kun je deze melding negeren.",
    ["MESSAGE_GOLD_MINES_GOLD_AWARDED"] = "{p1} krijgt een goudstaaf omdat hij de macht had over een afgebouwd project.",
    ["MESSAGE_GOLD_MINES_TAKE_GOLD_PROMPT"] = "{p1} mag een goudstaaf kiezen omdat hij de macht heeft over een afgebouwd project.",
    ["MESSAGE_WAGON_PROMPT"] = "De transportwagen van {p1} is klaar en mag nu op een aangrenzend project gezet worden.",
    ["MESSAGE_WAGON_NO_FEATURES"] = "De transportwagen van {p1} is klaar, maar er zijn geen beschikbare aangrenzende projecten.",
    ["MESSAGE_COC_TO_CITY_PROMPT"] = "De door {p1} gelegde tegel leverde alleen anderen punten op. {p1} mag nu, indien gewenst, een meeple in de Stad Carcassonne zetten",
    ["MESSAGE_COC_COUNT_PROMPT"] = "{p1} mag nu, indien gewenst, de Graaf verzetten.",
    ["MESSAGE_NO_STARTING_TILESET"] = "Kan spel niet starten zonder starttegel(s).",
    ["MESSAGE_NO_TILES"] = "Het spel kan niet starten zonder tegels.",
    ["MESSAGE_AI_INCOMPATIBLE_EXPANSIONS"] = "Kan geen AI-spel starten met incompatible uitbreidingen: {s1}.",
    ["MESSAGE_HILL_WARNING_NO_TILESTACK"] = "Waarschuwing: Er is een heuvel getrokken, maar de tegelstapel kan niet worden gevonden. Dit kan gebeuren als de tegelstapel nog maar 1 tegel heeft of geen. Als er nog 1 tegel over is, moet die handmatig onder de heuvel gelegd worden.",
    ["MESSAGE_SHEPHERD_ERROR_NO_SHEEP_BAG_RETURNING"] = "Fout: de zak met schapenfiches ontbreekt! De zak moet op tafel blijven om schapenfiches te kunnen retourneren.",
    ["MESSAGE_SHEPHERD_ERROR_NO_SHEEP_BAG_DRAWING"] = "Fout: de zak met schapenfiches ontbreekt! De zak moet op tafel blijven om schapenfiches te kunnen trekken.",
    ["MESSAGE_ROBBER_BARON_ERROR_MISSING"] = "Fout: de Roofridder ontbreekt! Het fiche moet op tafel blijven om toegekend te worden.",
    ["MESSAGE_KING_ERROR_MISSING"] = "Fout: de Koning ontbreekt! Het fiche moet op tafel blijven om toegekend te worden.",
    ["MESSAGE_TRADE_TOKENS_ERROR_MISSING"] = "Fout: {s1}s ontbreken! Deze moeten op tafel blijven om handelswaren te kunnen trekken.",
    ["MESSAGE_TOWER_ERROR_MISSING_CAPTURE"] = "FOUT: Kan de gevangennemer van de gevangene niet vinden.",

      --Hint Markers

    ["MESSAGE_HINTS_NO_TILE_LOCATION"] = "Er is geen geldige locatie waar deze tegel gelegd kan worden. Als de tegel van de stapel getrokken is, plaats deze dan terug, schud en trek er nog één.",
    ["MESSAGE_HINTS_STARTING_TILE"] = "Je mag deze starttegel overal neerzetten. Het is aan te raden dat ongeveer in het midden van de tafel te doen.",
    ["MESSAGE_HINTS_MAGIC_PORTAL_CALCULATING"] = "Bezig met berekenen van alle mogelijke locaties voor de magische poort. Hints zijn mogelijk vertraagd...",
    ["MESSAGE_HINTS_NO_FIGURE_LOCATION"] = "Er zijn geen geldige plekken om dit speelstuk neer te zetten. Als geen enkel ander speelstuk geldige locaties heeft, zul je het zetten van een speelstuk over moeten slaan.",
    ["MESSAGE_HINTS_TOWER_CALCULATING"] = "Bezig met berekenen van alle mogelijke locaties voor torendelen. Hints zijn mogelijk vertraagd...",
    ["MESSAGE_HINTS_NO_FAIRY_LOCATION"] = "Er is geen geldige locatie om de fee neer te zetten. De fee kan alleen naast een eigen meeple staan.",
    ["MESSAGE_HINTS_COC_CALCULATING"] = "Bezig met berekenen van alle mogelijke locaties. Hints zijn mogelijk vertraagd...",

      --Move Validation

    ["MESSAGE_FLIER_PLACED"] = "{f1} van {c1} is op een vliegtuig gezet.",
    ["MESSAGE_TOWER_PLACED"] = "Toren gestart op een torenbouwplaats.",
    ["MESSAGE_TOWER_INCREASED"] = "De toren is met een torendeel verhoogd.",
    ["MESSAGE_FIGURE_PLACED"] = "{f1} van {c1} is op {s2} gezet.",
    ["MESSAGE_SHRINE_CHALLENGED"] = "De {f1} van {c1} op {s2} wordt uitgedaagd!",
    ["MESSAGE_COUNT_PLACED"] = "{f1} is op {s2} gezet.",
    ["MESSAGE_INVALID_LOCATION_FAIRY"] = "Ongeldige locatie: de fee moet op een tegel met een eigen meeple gezet worden.",
    --This error is printed when you try to put a figure in the middle of a split feature, like the field on the left side of this tile: https://s20.postimg.cc/lusnmnm3x/Hills_Sheep_Weird_Cities3.png
    ["MESSAGE_INVALID_LOCATION_MIDDLE"] = "Ongeldige locatie: het midden van deze tegel kan niet gebruikt worden. Het speelstuk moet aan een van de zijkanten gezet worden.",
    ["MESSAGE_FIGURE_PLACED_BEFORE_TILE"] = "Er moet eerst een tegel gelegd worden voordat er een speelstuk kan worden gezet.",
    --After dropping a figure there is a short delay. If someone changes their mind and picks up the figure again before the end of the delay, this message is printed.
    ["MESSAGE_FIGURE_PICKED_UP"] = "Speelstuk weer opgepakt vóór controle. Plaats het speelstuk a.u.b. opnieuw.",
    ["MESSAGE_WAGON_ILLEGAL_FIGURE"] = "Alleen de transportwagen kan op dit moment gezet worden.",
    --This error is printed when you try to put a figure in the middle of a split feature, like the field on the left side of this tile: https://s20.postimg.cc/lusnmnm3x/Hills_Sheep_Weird_Cities3.png
    ["MESSAGE_INVALID_LOCATION_FLIER_MIDDLE"] = "Ongeldige locatie: plaats de meeple waarmee je wilt vliegen aan de ene of aan de andere zijde van het project.",
    --ie. if someone rolls a 3 they must put the flier on the tile 3 spaces in that direction. If they try to place on another this message is printed
    ["MESSAGE_INVALID_LOCATION_FLIER_WRONG_TILE"] = "Ongeldige locatie: het speelstuk moet op de tegel gezet worden die overeenkomt de de worp van de vliegtuigdobbelsteen.",
    ["MESSAGE_FLIER_WRONG_FIGURE"] = "Alleen de meeple die op de vliegtuigtegel gezet was kan verzet worden.",
    ["MESSAGE_ERROR_NO_SCRIPT_DATA"] = "Fout: Deze tegel heeft geen scriptgegevens. Deze uitbreiding is waarschijnlijk nog niet geïmplementeerd.",
    ["MESSAGE_INVALID_LOCATION_TILE_NOT_ALIGNED"] = "Ongeldige locatie: de tegel ligt niet goed op het raster.",
    --After dropping a tile there is a short delay. If someone changes their mind and picks up the tile again before the end of the delay, this message is printed.
    ["MESSAGE_TILE_PICKED_UP"] = "De tegel werd vóór controle weer opgeapakt. Leg de tegel opnieuw aan.",
    ["MESSAGE_INVALID_LOCATION_ABBEY"] = "Ongeldige locatie: de Abdij moet aan alle 4 de zijden omgeven worden door tegels.",
    ["MESSAGE_INVALID_LOCATION_SHRINE_CLOISTER"] = "Ongeldige locatie: er mag niet meer dan één klooster naast een cultusplaats liggen of omgekeerd.",
    ["MESSAGE_INVALID_LOCATION_RIVER_U_TURN"] = "Ongeldige locatie: U-bochten zijn niet toegestaan in de rivier.",
    ["MESSAGE_INVALID_LOCATION_RIVER_UNCONNECTED"] = "Ongeldige locatie: de tegel moet de bestaande rivier verlengen.",
    ["MESSAGE_INVALID_LOCATION_TILE_FEATURES_DONT_MATCH"] = "Ongeldige locatie: de naastgelegen tegel komt niet overeen.",
    ["MESSAGE_INVALID_LOCATION_TILE_OUT_OF_BOUNDS"] = "Ongeldige locatie: de tegel moet op het blauwe speelveld gelegd worden.",
    ["MESSAGE_INVALID_LOCATION_TILE_NOT_ADJACENT"] = "Ongeldige locatie: de nieuwe tegel moet tegen tenminste één bestaande tegel gelegd worden.",
    ["MESSAGE_INVALID_LOCATION_TILE_LOCATION_TAKEN"] = "Ongeldige locatie: er ligt hier al een tegel.",
    ["MESSAGE_INVALID_LOCATION_FIGURE_WRONG_TILE"] = "Ongeldige locatie: de speelfiguur moet op de zojuist aangelegde tegel gezet worden.",
    ["MESSAGE_INVALID_LOCATION_MAGIC_PORTAL_USAGE_EXCEEDED"] = "Ongeldige locatie: per beurt kan maar één meeple gebruik maken van de magische poort.",
    ["MESSAGE_INVALID_LOCATION_FIGURE_ON_DRAGON"] = "Ongeldige locatie: de speelfiguur kan niet op de tegel met de draak gezet worden.",
    ["MESSAGE_INVALID_LOCATION_FIGURE_ON_RIVER"] = "Ongeldige locatie: de rivier kan niet bezet worden.",
    ["MESSAGE_INVALID_LOCATION_COC_NOT_ALLOWED"] = "Ongeldige locatie: in dit stadium van het spel kan er geen speelfiguur in de Stad Carcassonne gezet worden.",
    ["MESSAGE_INVALID_LOCATION_FLIER_USAGE_EXCEEDED"] = "Ongeldige locatie: per beurt mag maar een meeple gebruik maken van een vliegtuig.",
    ["MESSAGE_INVALID_LOCATION_FLIER_ILLEGAL_FIGURE"] = "Ongeldige locatie: alleen de volgende meeples kunnen op het vliegtuig gezet worden: gewone meeple, grote meeple, transportwagen, burgemeester, volgeling.",
    ["MESSAGE_INVALID_LOCATION_FLIER_DISABLED"] = "Het vliegtuig is uitgeschakeld in het controlepaneel. Het is niet mogelijk een meeple op het vliegtuig te zetten.",
    ["MESSAGE_INVALID_LOCATION_TOWER_ILLEGAL_FIGURE"] = "Ongeldige locatie: alleen torendelen kunnen op een torenbouwplaats gezet worden. Op een bestaande toren kan alleen een torendeel, een gewone meeple, een grote meeple of een volgeling gezet worden.",
    ["MESSAGE_INVALID_LOCATION_TOWER_ALREADY_OCCUPIED"] = "Ongeldige locatie: er staat al een meeple op deze toren.",
    ["MESSAGE_INVALID_LOCATION_TOWER_FIGURE_BEFORE_TOWER"] = "Ongeldige locatie: meeples kunnen niet op torenbouwplaatsen gezet worden.",
    ["MESSAGE_INVALID_LOCATION_SHEPHERD"] = "Ongeldige locatie: de Herder kan alleen op een weide gezet worden.",
    ["MESSAGE_INVALID_LOCATION_ABBOT"] = "Ongeldige locatie: de Abt kan alleen op een klooster of tuin gezet worden.",
    ["MESSAGE_INVALID_LOCATION_GARDEN"] = "Ongeldige locatie: alleen de Abt kan op een tuin gezet worden.",
    ["MESSAGE_INVALID_LOCATION_BUILDER"] = "Ongeldige locatie: de Bouwmeester kan alleen op wegen of steden gezet worden.",
    ["MESSAGE_INVALID_LOCATION_PIG"] = "Ongeldige locatie: het Varken kan alleen op een weide gezet worden.",
    ["MESSAGE_INVALID_LOCATION_MAYOR"] = "Ongeldige locatie: de Burgemeester kan alleen op een stad gezet worden.",
    ["MESSAGE_INVALID_LOCATION_WAGON"] = "Ongeldige locatie: de Transportwagen kan niet op een weide staan.",
    ["MESSAGE_INVALID_LOCATION_FEATURE_DISABLED"] = "Ongeldige locatie: via de huisregels zijn {s1} uitgeschakeld.",
    ["MESSAGE_INVALID_LOCATION_BARN"] = "Ongeldige locatie: de Herenboerderij kan alleen op een kruispunt van weiden gezet worden.",
    ["MESSAGE_INVALID_LOCATION_MAGIC_PORTAL"] = "Ongeldige locatie: het is niet toegestaan om de magische poort te gebruiken om een meeple in een afgebouwd project te zetten.",
    ["MESSAGE_INVALID_LOCATION_BUILDER_NO_PARENT"] = "Ongeldige locatie: de Bouwmeester kan alleen op een weg of stad gezet worden met tenminste één eigen meeple.",
    ["MESSAGE_INVALID_LOCATION_PIG_NO_PARENT"] = "Ongeldige locatie: het Varken kan alleen op een weide met tenminste één eigen boer gezet worden.",
    ["MESSAGE_INVALID_LOCATION_FEATURE_ALREADY_OCCUPIED"] = "Ongeldige locatie: project is al bezet.",
    ["MESSAGE_INVALID_LOCATION_WAGON_NOT_CONNECTED"] = "Ongeldige locatie: niet door een weg aan het vorige project verbonden.",
    ["MESSAGE_INVALID_LOCATION_WAGON_ALREADY_COMPLETE"] = "Ongeldige locatie: dit project is al afgebouwd. De transportwagen moet op een niet afgebouwd project gezet worden.",
    ["MESSAGE_INVALID_LOCATION_FLIER"] = "Ongeldige locatie: een vliegtuigpassagier kan alleen op een stad, weg of klooster gezet worden.",
    ["MESSAGE_INVALID_LOCATION_FLIER_ALREADY_COMPLETE"] = "Ongeldige locatie: een vliegtuigpassagier mag alleen op een niet afgebouwd project gezet worden.",
    ["MESSAGE_INVALID_LOCATION_COC_ILLEGAL_FIGURE"] = "Ongeldige locatie: in dit stadium van het spel kan alleen één van de volgende meeples gezet worden: gewone meeple, grote meeple, transportwagen, burgemeester, volgeling.",
    ["MESSAGE_INVALID_LOCATION_COC_NOT_A_QUARTER"] = "Ongeldige locatie: de speelfiguur moet in één van de vier speciale stadswijken gezet worden.",
    ["MESSAGE_INVALID_LOCATION_COC"] = "Ongeldige locatie: in dit stadium van het spel kan een speelfiguur alleen in de Stad Carcassonne gezet worden.",
    ["MESSAGE_INVALID_LOCATION_WHEEL_CROWN"] = "Ongeldige locatie: alleen een gewone meeple, grote meeple of volgeling kan op een Kroon gezet worden.",
    ["MESSAGE_INVALID_LOCATION_WHEEL_CROWN_DISABLED"] = "De Kroon is uitgeschakeld in het regelpaneel. Er kan niets op gezet worden.",
    ["MESSAGE_INVALID_LOCATION_COC_ABBOT"] = "Ongeldige locatie: de Abt kan alleen de stadswijk Kathedraal gezet worden.",
    ["MESSAGE_INVALID_LOCATION_COC_MAYOR"] = "Ongeldige locatie: de Burgemeester kan alleen in de stadswijk Kasteel gezet worden.",
    ["MESSAGE_INVALID_LOCATION_COC_WAGON"] = "Ongeldige locatie: de Transportwagen kan niet in de stadswijk Markt gezet worden.",
    ["MESSAGE_INVALID_LOCATION_COC_ROADS_DISABLED"] = "Ongeldige locatie: wegen zijn momenteel uitgeschakeld in de huisregels, de stadwijk Smederij kan niet gebruikt worden.",
    ["MESSAGE_INVALID_LOCATION_COC_CITIES_DISABLED"] = "Ongeldige locatie: steden zijn momenteel uitgeschakeld in de huisregels, de stadswijk Kasteel kan niet gebruikt worden.",
    ["MESSAGE_INVALID_LOCATION_COC_FIELDS_DISABLED"] = "Ongeldige locatie: weiden zijn momenteel uitgeschakeld in de huisregels, de stadswijk Markt kan niet gebruikt worden.",
    ["MESSAGE_INVALID_LOCATION_COC_CLOISTERS_DISABLED"] = "Ongeldige locatie: kloosters zijn momenteel uitgeschakeld in de huisregels, de stadswijk Kathedraal kan niet gebruikt worden.",
    ["MESSAGE_COC_FROM_CITY_ILLEGAL_FIGURE"] = "Er kunnen nu alleen meeples uit de Stad Carcassonne gezet worden.",
    ["MESSAGE_INVALID_LOCATION_COC_FROM_WRONG_QUARTER"] = "Ongeldige locatie: deze speelfiguur stond in de stadswijk {f1} en kan alleen op een afgebouwde {s1} gezet worden.",
    ["MESSAGE_INVALID_LOCATION_COC_COMPLETED_ONLY"] = "Ongeldige locatie: meeples uit de Stad Carcassonne kunnen alleen op afgebouwde projecten gezet worden.",
    ["MESSAGE_INVALID_LOCATION_COC_END_GAME_INCOMPLETE_ONLY"] = "Ongeldige locatie: meeples uit de Stad Carcassone mogen alleen aan het einde van het spel op niet afgebouwde projecten gezet worden.",
    ["MESSAGE_INVALID_LOCATION_COC_LAST_TILE_ONLY"] = "Ongeldige locatie: meeples uit de Stad Carcassonne mogen alleen op projecten gezet worden die door de laatst gelegde tegel afgebouwd werden.",

      --Save Game

    ["MESSAGE_GAME_LOADED"] = "Spel geladen. Het is nu de beurt aan {p1}. Status: {s1}.",
    ["MESSAGE_GAME_LOADED_CONTROL"] = "{c1} wordt bestuurd door {p1}",
    ["MESSAGE_GAME_LOADED_REWIND_NOTIFICATION"] = "Merk op dat terugdraaien maar deels wordt ondersteund. Het kan zijn dat het nodig is bepaalde dingen op te ruimen als de toestand opgeslagen werd terwijl het script nog bezig was.",

      --Setup Game

    ["MESSAGE_SETUP_GAME_ALREADY_STARTED"] = "Het spel is al gestart. Start een nieuw spel om instellingen te wijzigen.",
    ["MESSAGE_SETUP_NO_CONTROL_PANEL_PERMISSIONS"] = "Alleen gepromoveerde spelers kunnen het regelpaneel gebruiken.",
    ["MESSAGE_SETUP_COLOR_SUBSTITUTION"] = "{c1} is van kleur/team gewisseld naar {c2}",
    ["MESSAGE_SETUP_MODEL_SUBSTITUTION"] = "{c1} heeft de figuur {f1} vervangen door een eigen model",
    ["MESSAGE_SETUP_RIVER_II_NOTIFICATION"] = "Er wordt gespeeld met de rivier. Leg een riviertegel en breid die uit. Volgens de regels moet de splitsing de eerste tegel zijn, gevolgd door de gedekte riviertegels totdat die op zijn, dan de bron en tot slot de tegel met het meer.",
    ["MESSAGE_SETUP_RIVER_NOTIFICATION"] = "Er wordt gespeeld met de rivier. Leg een riviertegel en breid die uit. Volgens de regels moet de bron de eerste tegel zijn, gevolgd door de gedekte riviertegels totdat die op zijn en tot slot de tegel met het meer.",
    ["MESSAGE_SETUP_START"] = "Het spel is gestart. Succes!",
    ["MESSAGE_SETUP_FIRST_PLAYER"] = "{p1} is willekeurig gekozen als eerste speler.",

      --State Machine

    ["MESSAGE_STATE_NEW_TURN"] = "----- Het is nu de beurt aan {p1} -----",
    ["MESSAGE_STATE_NEW_TURN_CONTROL"] = "----- {c1} wordt bestuurd door {p1} -----",
    ["MESSAGE_STATE_NEW_TURN_PLAYER_MISSING"] = "{c1} heeft geen besturende speler meer. Een andere speler kan deze plaats overnemen, de besturing kan aan een andere speler gegeven worden als medespeler of AI. Anders zal deze speler overgeslagen moeten worden.",
    ["MESSAGE_NO_GAME_BUTTON_PERMISSIONS"] = "Alleen gepromoveerde spelers kunnen deze knop gebruiken",
    ["MESSAGE_NO_BUTTON_PERMISSIONS"] = "Alleen de huidige speler of gepromoveerde spelers kunnen deze knop gebruiken",
    ["MESSAGE_GOLD_MINES_PLACE_GOLD_PROMPT"] = "Kies een plek om de goudstaaf te leggen",
    ["MESSAGE_LAKE_PLACE_FERRY_PROMPT"] = "Kies een route voor de veerboot",
    ["MESSAGE_BUILDER_PROMPT"] = "De Bouwmeester van {p1} geeft het recht om nog een tegel te trekken. Doe dit, samen met de gebruikelijke handelingen alvorens de beurt te eindigen.",
    ["MESSAGE_GAME_LOADED_DURING_SCORING"] = "Het geladen spel zat midden in de puntentelling. Speelstukken moeten mogelijk handmatig verwijderd worden. Het spel gaat verder alsof de puntentelling heeft plaatsgevonden. Het kan zijn dat er speelstukken zijn waarvan de punten niet zijn geteld.",
    ["MESSAGE_FIGURE_PROMPT"] = "Zet, indien gewenst, een speelfiguur.",
    ["MESSAGE_PHANTOM_PROMPT"] = "Zet, indien gewenst, de volgeling.",
    ["MESSAGE_FLIER_DIE_PROMPT"] = "Werp de vliegtuigdobbelsteen om de vliegafstand te bepalen.",
    ["MESSAGE_FLIER_PROMPT"] = "Zet de vliegtuigpassagier op de doeltegel.",
    ["MESSAGE_ERROR_NO_ACTION_FOR_STATE"] = "Fout: actie - {s1} bestaat niet in de huidige toestand - {s2}",
    ["MESSAGE_ERROR_NO_STATE"] = "Fout: huidige toestand bestaat niet - {s1}",

      --TTS Events

    ["MESSAGE_HOTSEAT_TAKEN"] = "De meespeelplek van {p1}, {c1}, is bezet.",
    ["MESSAGE_HOTSEAT_OWNER_MOVED"] = "De beheerder van meespeelplek {c1}, {c2}, heeft de tafel verlaten of is verplaatst.",
    ["MESSAGE_FLIER_DIE_ROLL"] = "{p1} heeft {n1} geworpen",
    ["MESSAGE_FLIER_WRONG_PLAYER_ROLLED"] = "FOUT: Het is momenteel niet jouw beurt OF je hebt de dobbelsteen geworpen zonder hem op te tillen.",
    ["MESSAGE_TILE_NOT_ALLOWED"] = "Het is momenteel niet toegestaan een tegel te leggen. Je mag alleen een tegel leggen aan het begin van je beurt. Huidige status: {s1}",
    ["MESSAGE_PHANTOM_NOT_ALLOWED"] = "Het is momenteel niet toegestaan om een volgeling te zetten. Je mag alleen een volgeling zetten na het zetten van een andere meeple. Huidige status: {s1}",
    ["MESSAGE_TOWER_NOT_ALLOWED"] = "Het is momenteel niet toegestaan om een torendeel te zetten. Dit mag gewoonlijk alleen na het leggen van een tegel. Huidige status: {s1}",
    ["MESSAGE_FIGURE_NOT_ALLOWED"] = "Het is momenteel niet toegestaan een speelfiguur te zetten. Dit mag gewoonlijk alleen na het leggen van een tegel. Huidige status: {s1}",
    ["MESSAGE_TOWER_WRONG_OWNER"] = "Deze toren is niet van jou. Controleer de kleur in de omschrijving.",
    ["MESSAGE_FIGURE_WRONG_OWNER"] = "Speelfiguur van de verkeerde kleur. Weet je zeker dat die van jou is?",
    ["MESSAGE_FAIRY_NOT_ALLOWED"] = "Het is momenteel niet toegestaan de fee te zetten. De fee mag alleen gezet worden na het leggen van een tegel. Huidige status: {s1}",
    ["MESSAGE_COUNT_NOT_ALLOWED"] = "Het is momenteel niet toegestaan de Graaf te verzetten. Je mag de Graaf alleen verzetten nadat je een meeple in de Stad Carcassonne gezet hebt. Huidige status: {s1}",
    ["MESSAGE_DROP_SPAM"] = "Meerdere speelstukken te snel gezet, even wachten.",
    ["MESSAGE_DROP_WRONG_PLAYER"] = "Het is momenteel niet jouw beurt. Gezette speelstukken tellen niet mee.",
    ["MESSAGE_DROP_GAME_NOT_STARTED"] = "Het spel is voorbij of nog niet gestart. Klik op de knop 'Spel starten' en leg de tegel opnieuw aan.",
    ["MESSAGE_TILE_REMOVED"] = "Tegel is verwijderd uit het raster.",
  },
  ['zh-tw'] = {
    ["AI/Hotseat (H)"] = "機器人(AI)/熱座(H)",
    --Player Colors
    ["Green"] = "綠色",
    ["Purple"] = "紫色",
    ["White"] = "白色",
    ["Blue"] = "藍色",
    ["Red"] = "紅色",
    ["Pink"] = "粉紅色",
    ["Magenta"] = "洋紅色",
    ["Yellow"] = "黃色",
    ["Orange"] = "橘色",
    ["Cyan"] = "青色",
    ["Teal"] = "藍綠色",
    ["Grey"] = "灰色",
    ["Black"] = "黑色",
    ["Brown"] = "棕色",
    ["Amber"] = "琥珀色",
    ["Rose"] = "玫紅色",
    ["Vermilion"] = "朱紅色",
    ["Chartreuse"] = "黃綠色",
    --AI Difficulties
    ["Easy"] = "容易",
    ["Hard (Beta)"] = "難 (試驗中)",
    --Figure Names
    ["Follower"] = "米寶", --"隨從",
    ["Followers"] = "米寶",
    ["Big Follower"] = "大米寶", --"大隨從",
    ["Builder"] = "工程師",
    ["Pig"] = "小豬",
    ["Mayor"] = "市長",
    ["Wagon"] = "馬車",
    ["Barn"] = "穀倉",
    ["Shepherd"] = "牧羊人",
    ["Messenger"] = "傳令使",
    ["Mage"] = "巫師",
    ["Mages"] = "巫師", --TEMP: for model substitution
    ["Witch"] = "女巫",
    ["Witches"] = "女巫", --TEMP: for model substitution
    ["Robber"] = "強盜", -- From mini-expansion: The Robbers
    ["Robbers"] = "強盜", -- From mini-expansion: The Robbers
    --Situational Figure Names
    ["Meeple"] = "米寶", --one of the 7 basic followers
    ["Farmer"] = "農夫", --follower in a field
    ["Knight"] = "騎士", --follower in a city
    --["Robber"] = "強盜", --follower on a road - Shared with Robber name from The Robber
    ["Monk"] = "僧侶", --follower in a cloister
    --Neutral Figure Names
    ["Dragon"] = "火龍",
    ["Fairy"] = "仙女",
    ["Count"] = "伯爵",
    ["Tower"] = "塔樓",
    ["Towers"] = "塔",
    ["Bridge"] = "橋",
    ["Bridges"] = "橋",
    ["Castle"] = "城堡",
    ["Castles"] = "城堡",
    ["Gold Bar"] = "金條",
    --Feature Names
    ["Field"] = "草原",
    ["Fields"] = "草原",
    ["City"] = "城市",
    ["Cities"] = "城市",
    ["Road"] = "道路",
    ["Roads"] = "道路",
    ["Cloister"] = "修道院",
    ["Cloisters"] = "修道院",
    --Situational Feature Names
    ["Farm"] = "田間", --field with a follower on it
    ["Farms"] = "田間", --field with a follower on it
    --Special Feature Names
    ["Cathedral"] = "主教教堂",
    ["Cathedrals"] = "主教教堂",
    ["Inn"] = "湖泊小旅館",
    ["Inns"] = "湖泊小旅館",
    ["Princess"] = "公主",
    ["Volcano"] = "火山",
    ["Portal"] = "傳送門", --魔法門 from big box 3 manual (bad translation?)
    ["Portals"] = "傳送門",
    ["Tower Foundation"] = "塔的地基",
    ["Abbey"] = "隱修院",
    ["Shrine"] = "神壇",
    ["Shrines"] = "神壇",
    ["Hill"] = "山丘",
    ["Hills"] = "山丘",
    ["Vineyard"] = "葡萄園",
    ["Vineyards"] = "葡萄園",
    ["Bazaar"] = "集市",
    ["Bazaars"] = "集市",
    ["Fliers"] = "飛人",
    ["Messages"] = "訊息",
    ["Ferries"] = "渡輪",
    ["Gold"] = "金條", --Should the special feature just be called gold bars?
    --City of Carcassonne Quarters
    ["Castle Quarter"] = "城堡區",
    ["Blacksmith Quarter"] = "鐵匠區",
    ["Cathedral Quarter"] = "教堂區",
    ["Market Quarter"] = "市場區",
    --Wheel of Fortune Features
    ["Crown"] = "王冠",
    ["Fortune"] = "幸運",
    ["Taxes"] = "稅收",
    ["Famine"] = "飢餓",
    ["Storm"] = "風暴",
    ["Inquisition"] = "宗教法庭",
    ["Plague"] = "瘟疫",
    --["Dragon"] = "火龍", --shared with figure name
    --Token Names
    ["Trade Goods"] = "商品",
    ["Wine Token"] = "酒桶幣",
    ["Cloth Token"] = "布匹幣",
    ["Wheat Token"] = "麥子幣",
    --currently excluding the token name for display in the control panel
    ["King"] = "國王",
    ["Robber Baron"] = "強盜男爵", --currently shared with follower on a road. Consider renaming to Robber Baron later and possibly having a unique translation
    ["Knock Out"] = "撞撞出局",
    ["Seduction"] = "誘惑交換",
    ["Target"] = "正中靶心",
    ["Catch"] = "接接樂",
    --Starting Tiles
    ["Starting Tiles"] = "起始牌",
    ["Base Starting Tile"] = "標準起始牌",
    ["The River"] = "河流一擴充",
    ["The River II"] = "河流二擴充",
    ["The River (Big Box 5)"] = "河流 (大盒版5)",
    ["City of Carcassonne"] = "卡卡頌市",
    ["School"] = "學校",
    ["Wind Roses"] = "風向玫瑰圖",
    ["Wheel of Fortune"] = "命運之輪",
    --Expansion Names
    ["Inns & Cathedrals"] = "主教擴充",
    ["Traders & Builders"] = "小豬擴充",
    ["The Princess & The Dragon"] = "火龍與公主",
    ["The Tower"] = "高塔陰影",
    ["Abbey & Mayor"] = "隱修院與市長",
    ["The Catapult"] = "投石器",
    ["Bridges, Castles, & Bazaars"] = "橋樑與市集",
    ["Hills & Sheep"] = "羊咩擴充",
    ["Count, King, & Robber"] = "伯爵國王與強盜",
    ["King & Robber Baron"] = "國王與強盜男爵擴充", --aka King & Scout, both unused.
    ["The Cathars"] = "異教徒擴充(圍城擴充)",
    ["The Count of Carcassonne"] = "伯爵擴充",
    ["The Cult, The Siege"] = "祭壇戰亂擴充", --??
    ["The Phantom"] = "鬼魂擴充",
    ["The Festival"] = "節慶擴充",
    ["The Flier"] = "飛人",
    ["The Messages"] = "傳令使",
    ["The Ferries"] = "渡輪",
    ["The Goldmines"] = "金礦",
    ["Mage & Witch"] = "法師和女巫",
    ["The Robbers"] = "強盜",
    ["Wheel of Fortune"] = "命運之輪", --Shared with starting tile name
    ["Crop Circles I"] = "麥田園一",
    ["Crop Circles II"] = "麥田園二",
    ["The Plague"] = "鼠疫",
    ["The Tunnel"] = "隧道擴充",
    --got many of the following from https://www.bger.org/thread-20997-1-1.html
    ["Little Buildings"] = "小建物",
    ["We Go to Carcassonne"] = "我們前往卡卡頌",
    ["The Besiegers"] = "圍攻",
    ["The German Monasteries"] = "修道院",
    ["The Abbot"] = "修道院長",
    ["Halflings I"] = "如此狂野的一半",
    ["Halflings II"] = "如此狂野的一半2",
    ["Darmstadt"] = "達姆施塔特",
    ["Spiel Promo"] = "遊戲展2014推廣板塊",
    ["Castles in Germany"] = "德國城堡",
    ['City Gates'] = "城門", --Die Stadttore in German. I believe this is a fan expansion.
    --Marker Types
    ["Both"] = "全部",
    ["None"] = "無",
    ["Scoring"] = "得分",
    ["Hints"] = "可放位置",

    --Button Labels

    ["BUTTON_LABEL_START_GAME"] = "開始遊戲",
    ["BUTTON_LABEL_END_GAME"] = "結束遊戲\n(計算成績)",
    ["BUTTON_LABEL_SCORE_SUMMARY"] = "計算總分",
    ["BUTTON_LABEL_SKIP_TURN"] = "跳過",
    ["BUTTON_LABEL_MARKERS"] = "標記:\n",
    ["BUTTON_LABEL_PROMPT_PLACE_FIGURE"] = "放置人物\n或",
    ["BUTTON_LABEL_SKIP_PLACING_FIGURE"] = "跳過放置人物",
    ["BUTTON_LABEL_PLACE_GOLD"] = "放置黃金",
    ["BUTTON_LABEL_SEDUCE_KNIGHT"] = "勾引騎士",
    ["BUTTON_LABEL_RETRIEVE_ABBOT"] = "取回修士",
    ["BUTTON_LABEL_PROMPT_PLACE_PHANTOM"] = "放置幽靈\n或",
    ["BUTTON_LABEL_SKIP_PHANTOM"] = "跳過放置幽靈",
    ["BUTTON_LABEL_SKIP_TOWER_CAPTURE"] = "跳過捕捉米寶",
    ["BUTTON_LABEL_PROMPT_REPLACE_WAGON"] = "重新放置您的馬車\n或",
    ["BUTTON_LABEL_SKIP_WAGON"] = "跳過放置馬車",
    ["BUTTON_LABEL_PROMPT_COC"] = "放置一個人物在卡卡頌市\n或",
    ["BUTTON_LABEL_PROMPT_MOVE_COUNT"] = "移動伯爵到另一區\n或",
    ["BUTTON_LABEL_SKIP_COUNT"] = "跳過移動伯爵",
    ["BUTTON_LABEL_RETURN_FOLLOWER"] = "歸還米寶",
    ["BUTTON_LABEL_CAPTURE"] = "捕捉{f1}",
    ["BUTTON_LABEL_RANSOM"] = "償還{f1}",
    ["BUTTON_LABEL_RETURN"] = "歸還{f1}",
    ["BUTTON_LABEL_EXPAND_FLOCK"] = "擴大羊群",
    ["BUTTON_LABEL_HERD_FLOCK"] = "將羊群取回得分",
    ["BUTTON_LABEL_TAKE_GOLD"] = "取回黃金",

    --UI Labels

    ["UI_AI_CALCULATING"] = "AI正在想下一步",

    --Control Panel Global

    ["TOOLTIP_ENABLE_ALL"] = "勾選所有選項",
    ["LABEL_TILES"] = "牌",
    ["TOOLTIP_NUM_TILES"] = "{n1}卡牌",
    ["LABEL_PREVIOUS_PAGE"] = "上一頁",
    ["LABEL_NEXT_PAGE"] = "下一頁",

    --Control Panel pg. 1

        --tooltips

    ["TOOLTIP_AI_HOTSEAT_TOGGLE"] = "按下按鈕來選擇AI難易度及有無:\nAI容易\nAI難\n熱座\n無",
    ["TOOLTIP_BASE_STARTING_TILE"] = "原始基本卡牌。",
    ["TOOLTIP_RIVER"] = "12張河流卡牌，在正常卡牌加入之前。",
    ["TOOLTIP_RIVER_II"] = "12張河流卡牌上若有分流，記號即把河流分成2等份，牧豬記號則給予農夫額外分數。",
    ["TOOLTIP_RIVER_BB5"] = "12張河流卡牌標有給牧羊人加分的額外羊隻圖案。",
    ["TOOLTIP_CITY_OF_CARCASSONNE"] = "卡卡頌市起始大卡牌-當您幫他人得分時，您可以選擇放置米寶在卡卡頌市大卡牌的任何一區。這些米寶可以在地標完成時，計分前移位到該區，得到/贏得分數。",
    ["TOOLTIP_WHEEL_OF_FORTUNE"] = "抽卡牌並旋轉命運之輪來得到機會。",

        --messages

    ["MESSAGE_SEAT_OCCUPIED"] = "已有玩家，無法設定熱座。",
    ["MESSAGE_SEAT_ASSIGNED_TO_AI"] = "{c1}已經被設定為人工智慧玩家，難易度：{s1}",
    ["MESSAGE_SEAT_ASSIGNED_TO_HOTSEAT"] = "{c1}已被設置為{p1}熱座玩家",
    ["MESSAGE_BASE_STARTING_TILE_NOT_ALLOWED"] = "你不能用基本的卡牌因為其他擴充起始卡牌已經被使用。",
    ["MESSAGE_BASE_STARTING_TILE_REMOVED"] = "你選的這些起始卡牌不能和基本卡牌並用，請移除基本卡牌。",
    ["MESSAGE_HOTSEAT_REMOVED"] = "{c1}不再是熱座完家",
    ["MESSAGE_TOWER_COUNT_CHANGED"] = "警告：因為新增或移除熱座/人工智慧玩家，塔數已改變成{n1}。",

    --Control Panel pg. 2

        --labels

    ["LABEL_BASE_GAME"] = "基礎遊戲",
    ["LABEL_MAJOR_EXPANSIONS"] = "主要擴充",

        --tooltips

    ["TOOLTIP_FOLLOWER"] = "隨從 - 此米寶身分是最基本的玩家，他們可以被用來佔領任何的城市、道路、土地、和修道院。",
    ["MESSAGE_FOLLOWER_COUNT_WARNING"] = "警告：強烈建議將米寶人數保持在7",
    ["MESSAGE_FOLLOWER_DISABLED_WARNING"] = "警告：強烈建議不要關閉米寶功能",
    ["TOOLTIP_BIG_FOLLOWER"] = "隨從 - 大米寶相當於兩個米寶，一個米寶佔領的土地只需要一個大米寶就能掠奪。就算玩家有兩個米寶佔領，一個大米寶就能打平，點數平分。",
    ["TOOLTIP_INN"] = "有旅館圖案遠在一旁的道路，在道路完成時將能有兩倍的點數，若沒有完成則無任何點數。",
    ["TOOLTIP_CATHEDRAL"] = "有主教教堂的城市完成時將有3倍點數，但城市若沒完成則沒有任何點數。",
    ["TOOLTIP_BUILDER"] = "特殊角色 - 建築師可以被放在任何已經有你的米寶的道路或城市上。放置後只要你放置卡牌在此道路或城市，你將能再抽取一張額外卡牌並執行動作。",
    ["TOOLTIP_PIG"] = "特殊角色 - 小豬可以被放在已經有米寶佔有土地的任何地方。遊戲結束的時候，任何有同玩家小豬在的土地都可以多1分",
    ["TOOLTIP_TRADE_GOODS"] = "在小豬擴充裡，當玩家完成城市時（無論是否由該玩家佔有），他們將獲得一個商品代幣。擁有每種類型最多的玩家將在遊戲結束時獲得10分。停用此功能不會讓包含商品的卡牌消失，只是讓商品代幣不被授予。",
    ["TOOLTIP_DRAGON"] = "繪有火山的卡牌會召喚龍。召喚龍之後，抽到繪有龍圖標的卡牌時，玩家將龍移動6次。龍移動到的卡牌上大部分的人物會被吃掉。詳細信息，請參閱規則",
    ["TOOLTIP_FAIRY"] = "可以選擇以移動仙女來代替放置一個人物。仙女會做3件事：回合開始時給她旁邊的人物1分，當地標完成時給3分，並保護卡牌免受龍的傷害。",
    ["TOOLTIP_MAGIC_PORTAL"] = "當抽到魔法門戶卡牌時，人物可以放置在該卡牌或任何已經放的任何其他卡牌塊上。但其他關於人物放置的規則仍然須遵守。",
    ["TOOLTIP_PRINCESS"] = "抽到有公主圖案卡牌時，玩家可以選擇從相連的城市移除一個騎士（米寶），或是放置人物。",
    ["TOOLTIP_TOWER"] = "塔 - 塔可以放置在塔的地基或另一個塔上以俘虜米寶。塔樓越高，其範圍就越大。",

        --messages

    ["MESSAGE_TOWER_COUNT_WARNING"] = "警告：強烈建議將塔數保留為原先值",

    --Control Panel pg. 3

        --labels

    ["LABEL_ROBBER_BARON_SHORT_NAME"] = "強盜男爵", -- This is the shortened form of "Robber Baron", since it doesn't fit on the control panel. In Chinese it is not shortened.

        --tooltips

    ["TOOLTIP_ABBEY"] = "隱修院是特殊的卡牌，玩家可以選擇抽一張卡牌或者是放隱修院卡牌。隱修院卡牌只能在有四面環繞其他卡牌的情況下才能放置。一旦隱修院放置，周圍四張卡牌的地標（道路，城市，田地）都視為完成。米寶可以被放置在隱修院(九宮格完成)",
    ["TOOLTIP_MAYOR"] = "人物 - 市長只能放在城市。城市中每有幾個盾牌記號他的強度就相當於有幾個米寶。",
    ["TOOLTIP_WAGON"] = "馬車- 馬車只能放在城市，道路和修道院上。它的得分與一般人物完全相同。但是，一旦得分，馬車就可以移動到任何連接的地標上。如果它直接接觸道路，兩個地標相連。請參閱規則了解更多詳情。",
    ["TOOLTIP_BARN"] = "特殊卡牌 - 穀倉只能放置在4個只有單純土地的卡牌角落。此土地中的任何都會立即進行評分並移除。之後連接到此土地的中的所有人物也將被計分並移除，但是得分較少。在遊戲結束時，穀倉所占土地上每個完成城市的將會得4分。詳細信息，請參閱規則。",
    ["TOOLTIP_KING"] = "國王令牌是獎勵給完成最大城市（最多卡牌組成）的玩家。如果有人完成一個更大的城市，則轉移令牌。在遊戲結束時，有令牌的玩家會在整個遊戲中因每一個完成的城市而有一分。",
    ["TOOLTIP_ROBBER_BARON"] = "強盜男爵令牌是獎勵給完成最長道路的玩家（最多卡牌組成）。如果有人完成更長的道路，則轉移令牌。在遊戲結束時，有令牌的玩家會在整個遊戲中因每一條完成的道路而有一分。",
    ["TOOLTIP_SHRINE"] = "6張聖壇卡牌。佔有在聖壇旁邊的修道院會增加難度，反之，佔有在修道院旁的聖壇也會增加難度。兩者之間第一個完成的將得分，而另一個則不會。",
    ["TOOLTIP_SHEPHERD"] = "特殊人物 - 牧羊人可以被放在田地裡。當放置時，玩家可隨機的抽一片羊圓板並將其添加到田地。每次牧羊人所有者在田地上添加一塊卡牌時，他們可以抽另一個羊圓板，如果玩家抽到了一隻狼，那麼所有的羊都會丟失，而牧羊人也會被撤離。請參閱規則了解更多細節。",
    ["TOOLTIP_HILL"] = "山丘是山丘和綿羊擴充的一個特徵。當玩家佔有考牌上任何一個項目（除了山丘本身）時，在平手時，佔有項目中有山丘團的玩家獲勝。若關閉此功能，玩遊戲時仍會有山丘和綿羊符號的卡牌，但並不會有任何作用。",
    ["TOOLTIP_VINEYARD"] = "葡萄園是山丘和綿羊擴充的特徵。當修道院的九宮格完成後，九宮格內的每個葡萄園將獲得額外的3分。如果修道院九宮格沒有完成，便不適用。有關詳細敘述請參考規則。關閉此選項還是會出現葡萄園圖案的卡牌，但並不會有任何作用",

        --messages

    ["MESSAGE_BASE_STARTING_TILE_NOT_COMPATIBLE_WITH_COC"] = "基礎起始卡牌不能與卡卡頌市合併使用。請移除基礎卡牌。",

    --Control Panel pg. 4

        --labels

    ["LABEL_MINI_EXPANSIONS"] = "迷你擴充",
    ["LABEL_WHEEL_SHORT_NAME"] = "命運之輪", -- This is the shortened form of "Wheel of Fortune", since it doesn't fit on the control panel. In Chinese it is not shortened.
    ["LABEL_WHEEL_TILES"] = "輪牌",

        --tooltips

    ["TOOLTIP_WHEEL_CROWN"] = "玩家可以選擇將追隨者放在畫有皇冠的空格而不是剛拼放的卡牌上，當移動大豬落在玩家放置的皇冠上時給予分數。",
    ["TOOLTIP_WHEEL_FORTUNE"] = "當大豬移動後停留在米寶（追隨者）所在位置，該玩家獲得3分或六分（兩格皇冠只有一名米寶的話）。",
    ["TOOLTIP_WHEEL_TAX"] = "當大豬移動的稅收圖案時，每個騎士（有盾牌的城堡米寶都為騎士）將為每個騎士帶來1分。",
    ["TOOLTIP_WHEEL_TILES"] = "含有幸運輪圖標的卡牌有19塊，這些卡牌上有旋轉命運之輪的步數。",
    ["TOOLTIP_WHEEL_FAMINE"] = "當大豬移動到飢荒事件時，農夫所躺的草原上每有一個完成的城市就獲得1分",
    ["TOOLTIP_WHEEL_STORM"] = "當大豬移動到暴雨事件時，每個玩家將面前每有一名尚未派遣的手下便得一分。",
    ["TOOLTIP_WHEEL_INQUISITION"] = "當大豬移動到迫害事件時，每位修士（在修道院的米寶）將獲得2分。",
    ["TOOLTIP_WHEEL_PLAGUE"] = "當大豬移動到鼠疫疫事件時，每個玩家必須從版圖上選任何一個米寶收回自己面前，順時鐘順序。",
    ["TOOLTIP_FLIER"] = "米寶可以放在紙飛機上面。當此情況發生時，會自動擲骰子看看米寶會飛幾格，甚至可以放在已被佔用的地方上（就算是修道院也可以，但土地不行)。",
    ["TOOLTIP_GOLD"] = "抽到帶有金色圖標的卡牌將獲得一個金條。相鄰的卡牌也將獲得一個金條。任何完成這些卡牌上的特色(城市，道路等)的玩家也都將獲得金幣，金幣在遊戲結束時會算分。",
    ["TOOLTIP_FERRY"] = "湖面受到郵輪控制，而郵輪將兩條路連接。然而，郵輪連接的路徑會隨著遊戲進行而改變。",
    ["TOOLTIP_FERRY"] = "湖面受到郵輪控制，而郵輪將兩條路連接。然而，郵輪連接的路徑會隨著遊戲進行而改變",

      --messages

    ["MESSAGE_BASE_STARTING_TILE_NOT_COMPATIBLE_WITH_WOF"] = "基礎起始卡牌不能與命運之輪合併使用。請移除基礎卡牌。",
    ["MESSAGE_WHEEL_DISABLED"] = "命運之輪沒有啟用時此選項無法啟用。",

    --Control Panel pg. 5

        --labels

    ["LABEL_MICRO_EXPANSIONS"] = "微型擴充",

        --tooltips

    ["TOOLTIP_GAMES_QUARTERLY"] = "10個特別的卡牌加到基礎卡牌裡。外加一個特殊的泉水卡牌，將土地與道路分開。",
    ["TOOLTIP_PHANTOMS"] = "幽靈可以在您放置一般人物後放置",
    ["TOOLTIP_SPIEL_PROMO"] = "單純的城市卡牌。",
    --["TOOLTIP_WE_GO_TO_CARCASSONNE"] = "2個獨特的卡牌 - 巴巴雅嘎小屋就像一個修道院，但是它的價值從10開始，每有相鄰的卡牌減少1個分。Bogatyr DONT UNDERSTNAD的選擇是一個4路公路連續3路路段在十字路口的第四條路。",

    --Control Panel pg. 6

        --labels

    ["LABEL_HOUSE_RULES"] = "客製規則",
    ["LABEL_DISABLE_FEATURE"] = "停用{s1}",
    ["LABEL_NERF_SMALL_CITIES"] = "削弱小城市",
    ["LABEL_REDUCE_TOWER_RANGE"] = "減少塔樓捕獲範圍",
    ["LABEL_RIVER_MIX_TILES"] = "混合所有河流卡牌",
    ["LABEL_RIVER_ALLOW_U_TURNS"] = "允許河流迴轉",
    ["LABEL_RIVER_ALLOW_UNCONNECTED"] = "允許河流斷開",
    ["LABEL_DISABLE_PIG_HERD"] = "關閉小豬群功能",
    ["LABEL_DISABLE_COUNT"] = "停用伯爵",

        --tooltips

    ["TOOLTIP_DISABLE_FEATURE"] = "不再允許將米寶放置在{s1}",
    ["TOOLTIP_NERF_SMALL_CITIES"] = "更改記分方式，僅包含2個卡牌的完成城市僅值2分。這與原始卡卡頌計分版本相同。",
    ["TOOLTIP_REDUCE_TOWER_RANGE"] = "如果勾選，塔範圍將從它所放置的卡牌開始，並從那裡開始增加。",
    ["TOOLTIP_RIVER_MIX_TILES"] = "如果勾選，所有河卡牌將會混合。",
    ["TOOLTIP_RIVER_ALLOW_U_TURNS"] = "如果勾選，便允許河流卡牌迴轉。但可能造成未來卡牌無適當處可放置。請自行斟酌。",
    ["TOOLTIP_RIVER_ALLOW_UNCONNECTED"] = "如果勾選， 河流卡牌便不需要承接上一張河流卡牌。 ",
    ["TOOLTIP_DISABLE_PIG_HERD"] = "此選項將關閉小豬群功能，每個城市的農夫不會因此增加一分。",
    ["TOOLTIP_DISABLE_COUNT"] = "此選項將停用伯爵",

    --Game Messages

        --AI

    ["MESSAGE_AI_CALCULATING"] = "AI玩家正在計畫他們的下一步...",
    ["MESSAGE_AI_SKIPPING_FIGURE"] = "AI玩家決定不放任何東西。",
    ["MESSAGE_AI_RECALCULATING_ODDS"] = "錯誤：所剩的卡牌數量與預期不同。若有人沒有依照順序或規定抽取卡牌，就會發生這種情況。正在重新計算...",
    ["MESSAGE_AI_FINISHED_RECALCULATING_ODDS"] = "完成重新計算賠率。AI玩家現在重新決定下一步如何進行。",
    ["MESSAGE_AI_GAME_OVER"] = "AI玩家無法找到剩餘卡牌。遊戲結束。",
    --used for displaying an imitated message from a player
    ["{c1}: {s1}"] = "{c1}: {s1}",
    ["MESSAGE_AI_NO_LOCATION"] = "AI玩家找不到可防止卡牌的位置。將重新洗牌及抽牌。",
    ["MESSAGE_AI_ERROR_NO_TILESTACK"] = "錯誤：無法將此卡牌放回到卡牌堆裡。如果此圖塊是河流的一部分，則需要手動將其重新打包並讓AI玩家重新開始。如果此圖塊是遊戲中的最後一塊，你應該丟棄它並結束遊戲。否則，可能會出現問題；在這種情況下丟棄卡牌並跳過這一輪。如果還是沒有解決問題，就重新啟動遊戲。",

        --Feature Map Management

    ["MESSAGE_PLAY_AREA_SHIFTING"] = "正在移動遊戲區域以騰出更多的空間。",

        --Global

    ["MESSAGE_LAKE_TILE_BONUS_TURN"] = "因為放了火山河牌{p1}可以再行駛一次動作",
    ["MESSAGE_WHEEL_FORTUNE"] = "若大豬移動到命運事件，當下的玩家獲得3分。",
    ["MESSAGE_WHEEL_FORTUNE_SCORED"] = "{p1}移動到命運事件上獲得3分。",
    ["MESSAGE_WHEEL_EVENT_DISABLED"] = "{s1}事件目前已被停用。沒有任何事情發生。",
    ["MESSAGE_WHEEL_TAXES"] = "大豬移動到在稅收事件上。每個騎士（米寶在有盾牌記號的城堡中為騎士）將得1分。",
    ["MESSAGE_WHEEL_EVENT_SCORED"] = "{p1}為{s1}事件得{n1}分。",
    ["MESSAGE_WHEEL_FAMINE"] = "大豬移動到飢荒事件上。每個躺在土地上的米寶（農民）每完成一個城市將獲得1分。",
    ["MESSAGE_WHEEL_STORM"] = "大豬移動到風暴事件上。每個玩家面前每個未使用的米寶（追隨者）都得一分。",
    ["MESSAGE_WHEEL_INQUISITION"] = "大豬移動到迫害事件上。每名僧侶（在教堂的人米寶）將獲得2分。",
    ["MESSAGE_WHEEL_INQUISITION_SCORED"] = "{p1}的米寶因為 {s1}事件得{n1}分",
    ["MESSAGE_WHEEL_PLAGUE"] = "大豬移動到鼠疫事件上。每個玩家必須從一塊遊戲版圖上拿回1個米寶（追隨者）。",
    ["MESSAGE_WHEEL_PLAGUE_PLAYER_SKIPPED"] = "{p1}沒有任何米寶在版圖上，可以跳過鼠疫事件的處罰。",
    ["MESSAGE_WHEEL_PLAGUE_FOLLOWER_AUTOMATICALLY_REMOVED"] = "{p1}只有有1名米寶在版圖上，因鼠疫事件發生，它已被移除。",
    ["MESSAGE_WHEEL_PLAGUE_PROMPT"] = "因為鼠疫事件的發生{p1}必須選擇一個米寶來移除。",
    ["MESSAGE_WHEEL_PLAGUE_REMOVAL"] = "{c1}{f1}因鼠疫事件而被移除。",
    ["MESSAGE_WHEEL_CROWN_SCORED"] = "{p1}的米寶因為{s1}皇冠得{n1}分",
    ["MESSAGE_DRAGON_AWAKENED"] = "龍已甦醒！",
    ["MESSAGE_DRAGON_MOVING"] = "龍正在移動！",
    ["MESSAGE_DRAGON_TILE_DRAWN_BEFORE_AWAKENED"] = "龍卡牌被抽出，但龍尚未醒來。允許將卡牌放回，洗牌並重抽。",
    ["MESSAGE_DRAGON_TILE_PLAYED_BEFORE_AWAKENED"] = "有人使用了龍卡牌，但龍尚未醒來。",
    ["MESSAGE_DRAGON_MOVES_REMAINING"] = "龍移動步數倒數{n1}步。換{p1}移動。",
    ["MESSAGE_DRAGON_STUCK"] = "龍沒有地方可以移動，所以動作結束。",
    --{n1} is the number of figures. {f1} is the name of the figure. ie. "5 sheep have been eaten..."
    ["MESSAGE_DRAGON_SHEEP_EAT_MESSAGE"] = "{n1}{f1}被龍吃掉了！好好吃喔~",
    --{c1} is the description of the figure (ie. Red). {f1} is the name of the figure. ie. "Red Follower has been eaten..."
    ["MESSAGE_DRAGON_FIGURE_EAT_MESSAGE"] = "{c1}{f1}被龍吃掉了！好好吃喔~",
    ["MESSAGE_DRAGON_COC_PROTECTION"] = "{c1}{f1}受到保護，不會被卡卡頌市的龍傷害。",
    ["MESSAGE_SKIP_FAIRY_CONFIRMATION"] = "You currently have the option to move the fairy. Are you sure you want to skip? Click again to confirm.",
    ["MESSAGE_ROBBER_BARON_AWARD"] = "{p1}完成最長的道路（{n1}張卡牌），已被授予強盜男爵令牌。",
    ["MESSAGE_KING_AWARD"] = "{p1}完成最大城市（{n1}張卡牌），已被授予的國王令牌。",
    ["MESSAGE_TRADE_TOKEN_AWARD"] = "{p1}完成城市，已被授予{s1}。",
    ["MESSAGE_PRINCESS_SEDUCTION_WAGON"] = "{c1}{f1}被公主誘惑!所有車伕....嗯..假裝沒這回事吧!",
    ["MESSAGE_PRINCESS_SEDUCTION"] = "{c1}{f1}被公主誘惑啦....嗚~嘿嘿",
    ["MESSAGE_ABBOT_RETRIEVE"] = "{p1}取回修道院長並因{s1}得{n1}分。",
    ["MESSAGE_TOWER_CAPTURE"] = "{c1}{f1}被{p1}抓走。",
    ["MESSAGE_TOWER_SELF_CAPTURE"] = "{c1} {f1}被自己的主人捕捉,已歸還到米寶堆",
    ["MESSAGE_TOWER_RANSOM"] = "{c1}{f1}已用3分從{c2}取回。",
    ["MESSAGE_TOWER_EXCHANGE_FOLLOWER"] = "{p1}{p2}將對方的米寶歸還。",
    ["MESSAGE_TOWER_EXCHANGE_PROMPT"] = "{p1}必須從{p2}中選取俘虜來交換。",
    ["MESSAGE_TOWER_EXCHANGE"] = "{c1}{f1}因釋放俘虜而被歸還。",
    ["MESSAGE_DEPENDENT_FIGURE_REMOVED"] = "{p1}沒有米寶可以給{f1}了，同時也需被移除。",
    ["MESSAGE_SHEPHERD_PROMPT"] = "{p1}加入他們的牧羊人的田地，並有機會擴大羊群。",
    ["MESSAGE_SHEPHERD_FIELD_FULL"] = "沒有土地可以佔了，但你可以牧羊:)",
    ["MESSAGE_SCORE_SHEPHERD"] = "{p1}的牧羊人牧了{n1}隻羊，得{n1}分。",
    ["MESSAGE_SHEPHERD_WOLF"] = "{p1}牧羊人牧的羊，全被狼嚇走了，沒有得分。",
    ["MESSAGE_FLIER_LANDED_ON_DRAGON"] = "米寶飛行員直直的飛雞龍嘴巴啦!謝謝你空中快遞食物來。",
    ["MESSAGE_FLIER_NO_DESTINATION"] = "飛行員要去的卡牌沒有任何地方可以佔有，米寶歸回。",
    ["MESSAGE_FLIER_NO_TILE"] = "飛行員要去的方向沒有卡牌存在，米寶歸回。",
    ["MESSAGE_COC_FROM_CITY_PROMPT"] = "{p1}在卡卡頌市裡有一個人物可以被放置到完成的地標。",
    ["MESSAGE_COC_FROM_CITY_GAMEOVER_PROMPT"] = "{p1}在卡卡頌市裡有一個人物可以被放置到未完成的地標。",
    ["MESSAGE_SHRINE_LOSE"] = "{c1}{f1}在修道院挑戰中挑戰失敗。",
    ["MESSAGE_SCORE"] = "{p1}因為{f1}而得{n1}分。",
    ["MESSAGE_SCORE_TRADE_TOKENS"] = "{p1}因為有最多的{f1}而得{n1}分。",
    ["MESSAGE_SCORE_KING_OR_ROBBER_BARON"] = "{p1}因為有{f1}而得{n1}分。",
    ["MESSAGE_SCORE_MAYOR_NO_POINTS"] = "{p1}在{f1}中得0分，市長只能在有盾牌的城市得分。",
    ["MESSAGE_SCORE_FAIRY_IDLE"] = "{p1}得1分，因為輪到他的時候他的{f1}在仙女旁邊。",
    ["MESSAGE_SCORE_FAIRY_FINISH"] = "{p1}因為在得分時{f1}有在仙女旁邊，因此多得3分。",
    ["MESSAGE_SCORE_GOLD_MINES"] = "{c1}得{n1}分，因為{n2}個金條，每個{n3}值分。",
    --this is displayed as a line for each player on the scoreboard
    ["{n1} points - {p1}"] = "{n1}分 - {p1}",
    --this is displayed as a line for each player when printing the scores at the end of the game
    ["#{n1} - {n2} points - {c1} - {p1}"] = "#{n1} - {n2}分 - {c1} - {p1}",
    ["MESSAGE_GAME_OVER"] = "遊戲結束",
    ["MESSAGE_GAME_OVER_PROMOTE"] = "如果你喜歡我的程式請幫我按一個讚，如果你有遇到任何錯誤或需要修改的地方請上傳檔案並留言告訴我。如果你喜歡我的翻譯也請幫我按一個讚，歡迎到我的IG:JENNY_JNILIFE。",
    ["MESSAGE_FAIRY_WARNING_NO_TILESTACK"] = "警告：找不到卡牌堆。仙女沒有分。如果您剛剛放置了最後塊卡牌，則可以忽略此訊息。",
    ["MESSAGE_GOLD_MINES_GOLD_AWARDED"] = "{p1}因為控制一個完成地標而得到一條金條。",
    ["MESSAGE_GOLD_MINES_TAKE_GOLD_PROMPT"] = "{p1}可以選擇得到一條金條或控制一個完成地標。",
    ["MESSAGE_WAGON_PROMPT"] = "{p1}的馬車已完成，可以放回鄰近的地標。",
    ["MESSAGE_WAGON_NO_FEATURES"] = "{p1}的馬車已完但是沒有鄰近的地標可以被放置。",
    ["MESSAGE_COC_TO_CITY_PROMPT"] = "{p1}為其他玩家得分(自己沒有得分)，所以{c1}可以選擇在卡卡頌市裡放一個米寶。",
    ["MESSAGE_COC_COUNT_PROMPT"] = "{p1}可以移動伯爵。",
    ["MESSAGE_NO_STARTING_TILESET"] = "沒有任何版基礎牌組，遊戲無法開始。",
    ["MESSAGE_NO_TILES"] = "沒有任何卡牌，遊戲無法開始。",
    ["MESSAGE_AI_INCOMPATIBLE_EXPANSIONS"] = "人工智慧玩家還沒學會{s1}版本，遊戲無法開始",
    ["MESSAGE_HILL_WARNING_NO_TILESTACK"] = "警告:山丘卡牌被抽出但是找不到剩餘卡牌堆，有可能是因為只剩下一張，這時候請手動將最後一張卡牌放置在山丘卡牌底下。",
    ["MESSAGE_SHEPHERD_ERROR_NO_SHEEP_BAG_RETURNING"] = "錯誤:找不到羊群抽取包! 這個包必須存在以便羊小牌放回。",
    ["MESSAGE_SHEPHERD_ERROR_NO_SHEEP_BAG_DRAWING"] = "錯誤:找不到羊群抽取包! 這個包必須存在以便抽取羊小牌。",
    ["MESSAGE_ROBBER_BARON_ERROR_MISSING"] = "錯誤:找不到強盜男爵令牌!這個令牌必須存在以便獎勵。",
    ["MESSAGE_KING_ERROR_MISSING"] = "錯誤:找不到國王令牌!這個令牌必須存在以便獎勵。",
    ["MESSAGE_TRADE_TOKENS_ERROR_MISSING"] = "錯誤:找不到{s1}卡牌堆!卡牌堆必須存在以便交換商品。",
    ["MESSAGE_TOWER_ERROR_MISSING_CAPTURE"] = "錯誤:找不到俘虜。",

        --Hint Markers

    ["MESSAGE_HINTS_NO_TILE_LOCATION"] = "此卡牌沒有可放置位置。如果從卡牌堆中抽出，將其放回並洗牌，然後重抽一個。",
    ["MESSAGE_HINTS_STARTING_TILE"] = "您可以將此起始卡牌放在任何位置。建議將其放在中央附近。",
    ["MESSAGE_HINTS_MAGIC_PORTAL_CALCULATING"] = "計算所有可能放置魔術門戶的位置。提示可能會較慢......",
    ["MESSAGE_HINTS_NO_FIGURE_LOCATION"] = "此人物沒有可放置位置，如果沒有其他人物可以放置，請跳過放置人物。",
    ["MESSAGE_HINTS_TOWER_CALCULATING"] = "計算所有可能放置塔樓的位置。提示可能會較慢......",
    ["MESSAGE_HINTS_NO_FAIRY_LOCATION"] = "沒有可放置仙女的位置，仙女只能放置在您自己的人物旁。",
    ["MESSAGE_HINTS_COC_CALCULATING"] = "計算所有可能放置位置。提示可能會較慢......",

        --Move Validation

    ["MESSAGE_FLIER_PLACED"] = "{c1}{f1}被放置在飛行器上。",
    ["MESSAGE_TOWER_PLACED"] = "塔樓從塔的地基上開始。",
    ["MESSAGE_TOWER_INCREASED"] = "塔樓增加一層。",
    ["MESSAGE_FIGURE_PLACED"] = "{c1}{f1}被放在{s2}。",
    ["MESSAGE_SHRINE_CHALLENGED"] = "在{s2}上的{c1}{f1}被挑戰!",
    ["MESSAGE_COUNT_PLACED"] = "{f1}被放在{s2}。",
    ["MESSAGE_INVALID_LOCATION_FAIRY"] = "卡牌放置位置錯誤：仙女必須放在有您的米寶的卡牌上。",
    --This error is printed when you try to put a figure in the middle of a split feature, like the field on the left side of this tile: https://s20.postimg.cc/lusnmnm3x/Hills_Sheep_Weird_Cities3.png
    ["MESSAGE_INVALID_LOCATION_MIDDLE"] = "卡牌放置位置錯誤：此卡牌的中間位置是無效的地標。您必須將米寶放在地標的任一側。",
    ["MESSAGE_FIGURE_PLACED_BEFORE_TILE"] = "在放置人物之前必須先放置卡牌。",
    --After dropping a figure there is a short delay. If someone changes their mind and picks up the figure again before the end of the delay, this message is printed.
    ["MESSAGE_FIGURE_PICKED_UP"] = "人物太快移走。請重新放置。",
    ["MESSAGE_WAGON_ILLEGAL_FIGURE"] = "錯誤:您現在只能放置馬車",
    --This error is printed when you try to put a figure in the middle of a split feature, like the field on the left side of this tile: https://s20.postimg.cc/lusnmnm3x/Hills_Sheep_Weird_Cities3.png
    ["MESSAGE_INVALID_LOCATION_FLIER_MIDDLE"] = "卡牌放置位置錯誤：您必須將飛行器放在放在地標的任一側。",
    --ie. if someone rolls a 3 they must put the flier on the tile 3 spaces in that direction. If they try to place on another this message is printed
    ["MESSAGE_INVALID_LOCATION_FLIER_WRONG_TILE"] = "卡牌放置位置錯誤：您必須將人物放在與飛行器骰子數字相對應的卡牌上。",
    ["MESSAGE_FLIER_WRONG_FIGURE"] = "錯誤：您現在只能放置剛剛",
    ["MESSAGE_ERROR_NO_SCRIPT_DATA"] = "錯誤：這張擴充卡牌沒有程式碼設定",
    ["MESSAGE_INVALID_LOCATION_TILE_NOT_ALIGNED"] = "卡牌放置位置錯誤：卡牌未與設定網格對齊。",
    --After dropping a tile there is a short delay. If someone changes their mind and picks up the tile again before the end of the delay, this message is printed.
    ["MESSAGE_TILE_PICKED_UP"] = "卡牌太快移走。請重新放置。",
    ["MESSAGE_INVALID_LOCATION_ABBEY"] = "隱修院卡牌放置位置錯誤：修道院必須放置在四面環繞著卡牌的地方。",
    ["MESSAGE_INVALID_LOCATION_SHRINE_CLOISTER"] = "卡牌放置位置錯誤：修道院不能緊挨著神社，反之亦然。",
    ["MESSAGE_INVALID_LOCATION_RIVER_U_TURN"] = "卡牌放置位置錯誤：河流卡牌不允許迴轉。",
    ["MESSAGE_INVALID_LOCATION_RIVER_UNCONNECTED"] = "卡牌放置位置錯誤：卡牌必須繼續接續已被放置的河流卡牌。",
    ["MESSAGE_INVALID_LOCATION_TILE_FEATURES_DONT_MATCH"] = "卡牌放置位置錯誤：相鄰的卡牌不匹配。",
    ["MESSAGE_INVALID_LOCATION_TILE_OUT_OF_BOUNDS"] = "卡牌放置位置錯誤：卡牌必須放在藍色遊樂區塊。",
    ["MESSAGE_INVALID_LOCATION_TILE_NOT_ADJACENT"] = "卡牌放置位置錯誤：必須與至少另一個卡牌相鄰。",
    ["MESSAGE_INVALID_LOCATION_TILE_LOCATION_TAKEN"] = "卡牌放置位置錯誤：空間已被另一張卡牌佔用。",
    ["MESSAGE_INVALID_LOCATION_FIGURE_WRONG_TILE"] = "卡牌放置位置錯誤：您必須人物放在剛放置的卡牌上。",
    ["MESSAGE_INVALID_LOCATION_MAGIC_PORTAL_USAGE_EXCEEDED"] = "卡牌放置位置錯誤：每回合只有一名米寶可以使用魔法門戶。",
    ["MESSAGE_INVALID_LOCATION_FIGURE_ON_DRAGON"] = "卡牌放置位置錯誤：在有龍的卡牌不能放置一個人物。",
    ["MESSAGE_INVALID_LOCATION_FIGURE_ON_RIVER"] = "卡牌放置位置錯誤：您不能佔領一條河。",
    ["MESSAGE_INVALID_LOCATION_COC_NOT_ALLOWED"] = "卡牌放置位置錯誤：遊戲的這個階段您不能在卡卡頌市放置人物。",
    ["MESSAGE_INVALID_LOCATION_FLIER_USAGE_EXCEEDED"] = "卡牌放置位置錯誤：每回合只有一名米寶可以使用飛行功能。",
    ["MESSAGE_INVALID_LOCATION_FLIER_ILLEGAL_FIGURE"] = "卡牌放置位置錯誤：只有一名米寶可以放在飛行器上。有效的人物：米寶、大米寶、馬車、市長、幽靈。",
    ["MESSAGE_INVALID_LOCATION_FLIER_DISABLED"] = "飛行器在控制面板中停用。您不能在飛行器上放置任何東西。",
    ["MESSAGE_INVALID_LOCATION_TOWER_ILLEGAL_FIGURE"] = "卡牌放置位置錯誤：只有塔塊可以放在塔的地基上。塔樓上只能放置塔樓，大米寶和米寶。",
    ["MESSAGE_INVALID_LOCATION_TOWER_ALREADY_OCCUPIED"] = "卡牌放置位置錯誤：這座塔已經被佔領。",
    ["MESSAGE_INVALID_LOCATION_TOWER_FIGURE_BEFORE_TOWER"] = "卡牌放置位置錯誤：追隨者不能放在塔的地基上。",
    ["MESSAGE_INVALID_LOCATION_SHEPHERD"] = "卡牌放置位置錯誤：牧羊人只能被放在田野裡。",
    ["MESSAGE_INVALID_LOCATION_ABBOT"] = "卡牌放置位置錯誤：修道院長只能放在花園或修道院。",
    ["MESSAGE_INVALID_LOCATION_GARDEN"] = "卡牌放置位置錯誤：只有修道院長可以放在花園裡。",
    ["MESSAGE_INVALID_LOCATION_BUILDER"] = "卡牌放置位置錯誤：建築師只能放置在道路和城市。",
    ["MESSAGE_INVALID_LOCATION_PIG"] = "卡牌放置位置錯誤：小豬只能放在田裡",
    ["MESSAGE_INVALID_LOCATION_MAYOR"] = "卡牌放置位置錯誤：市長只能佔領一個城市。",
    ["MESSAGE_INVALID_LOCATION_WAGON"] = "卡牌放置位置錯誤：一輛馬車不能佔領田地。",
    ["MESSAGE_INVALID_LOCATION_FEATURE_DISABLED"] = "卡牌放置位置錯誤：{s1}因客製規則停用。",
    ["MESSAGE_INVALID_LOCATION_BARN"] = "卡牌放置位置錯誤：穀倉只能放在田野的一角。",
    ["MESSAGE_INVALID_LOCATION_MAGIC_PORTAL"] = "卡牌放置位置錯誤：您可能無法使用魔法門戶在已完成的地標上放置米寶。",
    ["MESSAGE_INVALID_LOCATION_BUILDER_NO_PARENT"] = "卡牌放置位置錯誤：建築師只能放置在包含至少一個您的米寶的道路/城市中。",
    ["MESSAGE_INVALID_LOCATION_PIG_NO_PARENT"] = "卡牌放置位置錯誤：小豬只能放在包含至少一個您的米寶的田地上。",
    ["MESSAGE_INVALID_LOCATION_FEATURE_ALREADY_OCCUPIED"] = "卡牌放置位置錯誤：此地已被佔用。",
    ["MESSAGE_INVALID_LOCATION_WAGON_NOT_CONNECTED"] = "卡牌放置位置錯誤：未通過道路連接到上一個地標。",
    ["MESSAGE_INVALID_LOCATION_WAGON_ALREADY_COMPLETE"] = "卡牌放置位置錯誤：此地標已經完成。馬車必須放置在不完整的地標上",
    ["MESSAGE_INVALID_LOCATION_FLIER"] = "卡牌放置位置錯誤：飛行器只能放在城市，道路或修道院上。",
    ["MESSAGE_INVALID_LOCATION_FLIER_ALREADY_COMPLETE"] = "卡牌放置位置錯誤：您可能只將飛行器放在不完整的地標上。",
    ["MESSAGE_INVALID_LOCATION_COC_ILLEGAL_FIGURE"] = "卡牌放置位置錯誤：只有特定人物才能在遊戲的這個階段。有效的人物：米寶、大米寶、馬車、市長、幽靈。",
    ["MESSAGE_INVALID_LOCATION_COC_NOT_A_QUARTER"] = "卡牌放置位置錯誤：這個人物必須放在特定的城市區域。",
    ["MESSAGE_INVALID_LOCATION_COC"] = "卡牌放置位置錯誤：在這個階段，人物只能被放在卡卡頌市內。",
    ["MESSAGE_INVALID_LOCATION_WHEEL_CROWN"] = "放置位置錯誤：只有米寶，大米寶和幽靈可以放在皇冠區。",
    ["MESSAGE_INVALID_LOCATION_WHEEL_CROWN_DISABLED"] = "皇冠區在控制面板中停用。您不能在皇冠區上放置任何東西。",
    ["MESSAGE_INVALID_LOCATION_COC_ABBOT"] = "卡牌放置位置錯誤：修道院長只能放在主教堂區。",
    ["MESSAGE_INVALID_LOCATION_COC_MAYOR"] = "卡牌放置位置錯誤：市長只能放在城堡區。",
    ["MESSAGE_INVALID_LOCATION_COC_WAGON"] = "卡牌放置位置錯誤：一輛馬車不能放在市場區。",
    ["MESSAGE_INVALID_LOCATION_COC_ROADS_DISABLED"] = "卡牌放置位置錯誤：道路目前在客製規則中被禁用。不能使用鐵匠區。",
    ["MESSAGE_INVALID_LOCATION_COC_CITIES_DISABLED"] = "卡牌放置位置錯誤：目前在客製規則中禁用了城市。不能使用城堡區。",
    ["MESSAGE_INVALID_LOCATION_COC_FIELDS_DISABLED"] = "卡牌放置位置錯誤：字段目前在客製規則中被禁用。無法使用市場區。",
    ["MESSAGE_INVALID_LOCATION_COC_CLOISTERS_DISABLED"] = "卡牌放置位置錯誤：修道院目前在客製規則中被禁用。不能使用主教堂區。",
    ["MESSAGE_COC_FROM_CITY_ILLEGAL_FIGURE"] = "錯誤：現在只能放置卡卡頌市的人物。",
    ["MESSAGE_INVALID_LOCATION_COC_FROM_WRONG_QUARTER"] = "卡牌放置位置錯誤：這個人物被置於{f1}，但這個人物只能被放在已完成的{s1}上。",
    ["MESSAGE_INVALID_LOCATION_COC_COMPLETED_ONLY"] = "卡牌放置位置錯誤：人物只能放置在完整的地標上。",
    ["MESSAGE_INVALID_LOCATION_COC_END_GAME_INCOMPLETE_ONLY"] = "卡牌放置位置錯誤：人物只能放置在不完整的地標上。",
    ["MESSAGE_INVALID_LOCATION_COC_LAST_TILE_ONLY"] = "卡牌放置位置錯誤：人物只能放置在剛剛放下的卡牌上。",

        --Save Game

    ["MESSAGE_GAME_LOADED"] = "遊戲已載入，現在換{p1}，{s1}",
    ["MESSAGE_GAME_LOADED_CONTROL"] = "{c1}被{p1}控制",
    ["MESSAGE_GAME_LOADED_REWIND_NOTIFICATION"] = "請注意，並不完全支持回返功能，假如遊戲狀態儲存時遊戲程式正在運作，你可能需要手動清理桌面",

        --Setup Game
    ["MESSAGE_SETUP_GAME_ALREADY_STARTED"] = "遊戲已開始,如要改變設定請開新遊戲",
    ["MESSAGE_SETUP_NO_CONTROL_PANEL_PERMISSIONS"] = "只有擁有權限的玩家可以使用控制版面",
    ["MESSAGE_SETUP_COLOR_SUBSTITUTION"] = "{c1}換成{c2}",
    ["MESSAGE_SETUP_MODEL_SUBSTITUTION"] = "{c1}的{f1}換成客製化的",
    ["MESSAGE_SETUP_RIVER_II_NOTIFICATION"] = "您現在正在玩河流卡牌。請放置河流卡牌。根據規則，河道分流應該是第一個放置的卡牌，接著是其他面朝下的河流卡牌，直到它們放置完畢，然後是泉湧，最後是湖。",
    ["MESSAGE_SETUP_RIVER_NOTIFICATION"] = "您現在正在玩河流卡牌。請放置河流卡牌。根據規則，泉湧應該是第一個放置的卡牌，接著是其他面朝下的河流卡牌，最後是湖。",
    ["MESSAGE_SETUP_START"] = "遊戲開始 加油!",
    ["MESSAGE_SETUP_FIRST_PLAYER"] = "{p1}被隨機選為第一位玩家。",

        --State Machine

    ["MESSAGE_STATE_NEW_TURN"] = "-----------現在換{p1}-----------",
    ["MESSAGE_STATE_NEW_TURN_CONTROL"] = "-------{c1}被{p1}控制------",
    ["MESSAGE_STATE_NEW_TURN_PLAYER_MISSING"] = "{c1}不被任何玩家控制。其他玩家可以選擇此顏色，或將此顏色給熱座或是電腦AI，否則此顏色應被跳過。",
    ["MESSAGE_NO_GAME_BUTTON_PERMISSIONS"] = "只有擁有權限的玩家可以控制此選項",
    ["MESSAGE_NO_BUTTON_PERMISSIONS"] = "只有玩家和有權限的玩家可以控制此選項",
    ["MESSAGE_GOLD_MINES_PLACE_GOLD_PROMPT"] = "請選擇一個金條放置地點",
    ["MESSAGE_LAKE_PLACE_FERRY_PROMPT"] = "請選擇一條郵輪的路徑",
    ["MESSAGE_BUILDER_PROMPT"] = "{p1}玩家的建築師讓他可以再抽一張牌，請再抽一張，並且在換玩家前執行如往常的選擇與動作",
    ["MESSAGE_GAME_LOADED_DURING_SCORING"] = "過去載入的遊戲正在計分，可能需要手動移除米寶，還沒計分的米寶可能會留在原位",
    ["MESSAGE_FIGURE_PROMPT"] = "您可以放置米寶",
    ["MESSAGE_PHANTOM_PROMPT"] = "您可以放置幽靈",
    ["MESSAGE_FLIER_DIE_PROMPT"] = "擲飛人骰字以決定步",
    ["MESSAGE_FLIER_PROMPT"] = "請把飛人移到骰出的目的地",
    ["MESSAGE_ERROR_NO_ACTION_FOR_STATE"] = "就{s2}狀況{s1}並不存在",
    ["MESSAGE_ERROR_NO_STATE"] = "目前{s1}階段不存在",

        --TTS Events

    ["MESSAGE_HOTSEAT_TAKEN"] = "{p1}的熱座，{c1}已經有人",
    ["MESSAGE_HOTSEAT_OWNER_MOVED"] = "{c1}的熱座擁有者，{c2}已經離桌或換位置",
    ["MESSAGE_FLIER_DIE_ROLL"] = "{p1}骰了{n1}",
    ["MESSAGE_FLIER_WRONG_PLAYER_ROLLED"] = "錯誤：現在還沒換到您，或是您沒有把骰子撿起就骰了骰子",
    ["MESSAGE_TILE_NOT_ALLOWED"] = "目前不允許放置卡牌。您只能在輪到您時放置卡牌。當前狀態：{s1}",
    ["MESSAGE_PHANTOM_NOT_ALLOWED"] = "目前不允許放置幽靈。你只能在放置米寶後才能放置幽靈。當前狀態：{s1}",
    ["MESSAGE_TOWER_NOT_ALLOWED"] = "目前不允許放置塔樓。您只能在放置卡牌後放置塔樓。當前狀態：{s1}",
    ["MESSAGE_FIGURE_NOT_ALLOWED"] = "目前不允許放置人物。通常只允許在放置卡牌後放置人物。當前狀態：{s1}",
    ["MESSAGE_TOWER_WRONG_OWNER"] = "這座塔樓不屬於你。請移動游標查看顏色。",
    ["MESSAGE_FIGURE_WRONG_OWNER"] = "放置錯誤的人物顏色。你確定這個顏色是你的嗎？",
    ["MESSAGE_FAIRY_NOT_ALLOWED"] = "目前不允許放置仙女。您只有在放置卡牌後才可以放置仙女。當前狀態：{s1}",
    ["MESSAGE_COUNT_NOT_ALLOWED"] = "目前不允許放置伯爵。在卡卡頌市放置一名米寶之後，您才被允許放置伯爵。當前狀態：{s1}",
    ["MESSAGE_DROP_SPAM"] = "操作複雜，請稍候。",
    ["MESSAGE_DROP_WRONG_PLAYER"] = "目前還沒輪到你。放置的都不算數。",
    ["MESSAGE_DROP_GAME_NOT_STARTED"] = "遊戲結束或尚未開始。按開始遊戲按鈕並重新放置卡牌。",
    ["MESSAGE_TILE_REMOVED"] = "卡牌從已設定好的網格中刪除。",
  }
}
